const Industries = [
    "Agriculture",
    "Arts",
    "Construction",
    "Consumer Goods",
    "Corporate Services",
    "Design",
    "Education",
    "Energy & Mining",
    "Entertainment",
    "Finance",
    "Health Care",
    "Legal",
    "Manufacturing",
    "Media & Communications",
    "Nonprofit",
    "Public Administration",
    "Public Safety",
    "Real Estate",
    "Recreation & Travel",
    "Retail & Wholesale",
    "Tech Software & IT Services",
    "Transportation & Logistics",
    "Wellness & Fitness"
  ];

  export type Subcategorytype={[key:string]:string[]} 

  const industriesSubcategories:Subcategorytype= {
    "Agriculture": [
      "Agriculture (Select All)",
      "Crop Production",
      "Animal Production", 
      "Forestry & Logging",
      "Fishing & Hunting",
      "Agricultural Support Activities",
      "Agro-Processing",
      "Agricultural Machinery",
      "Agricultural Chemicals",
      "Farm Supplies Wholesaling",
      "Agricultural R&D",
      "Agri-Tech & Digital Agriculture",
      "Agricultural Consulting & Services",
      "Agricultural Education & Training",
      "Organic Farming",
      "Sustainable Agriculture",
      "Urban Agriculture"
    ],
    "Arts": [
    "Arts (Select All)",
      "Visual Arts",
      "Performing Arts",
      "Literary Arts", 
      "Cinematic Arts",
      "Digital & Multimedia Arts",
      "Crafts",
      "Photography", 
      "Architecture & Design",
      "Fashion & Textile Arts",
      "Art Education & Therapy",
      "Cultural Heritage & Preservation",
      "Event & Festival Management",
      "Arts Administration & Management", 
      "Art Criticism & Journalism"
    ],
    "Construction": [
    "Construction (Select All)",
      "Building Construction",
      "Heavy & Civil Engineering", 
      "Specialty Trade Contractors",
      "Infrastructure",
      "Construction Services", 
      "Construction Materials & Equipment",
      "Real Estate Development & Management", 
      "Green & Sustainable Construction",
      "Construction Technology & Automation",
      "Restoration & Renovation", 
      "Disaster Relief & Reconstruction",
      "Modular & Prefabricated Construction"
    ],
    "Consumer Goods": [
    "Consumer Goods (Select All)",
      "Food & Beverage",
      "Personal Care & Household",
      "Apparel & Textiles", 
      "Consumer Electronics",
      "Home Furnishings & Improvement",
      "Toys & Recreational Products", 
      "Automobiles & Auto Parts",
      "Luxury Goods",
      "Pet Products", 
      "Baby Products",
      "Health & Wellness Products", 
      "Stationery & Office Supplies",
      "Durables & Appliances", 
      "Tobacco Products",
      "Travel Goods", 
      "Wine & Spirits"
    ],
    "Corporate Services": [
    "Corporate Services (Select All)",
      "Accounting",
      "Business Supplies & Equipment", 
      "Corporate Communications",
      "Environmental Services", 
      "Events Services",
      "Executive Office", 
      "Facilities Services",
      "Financial Services for Corporates", 
      "Human Resources",
      "Information Services", 
      "Management Consulting",
      "Marketing & Advertising", 
      "Outsourcing/Offshoring",
      "Public Affairs & Lobbying", 
      "Professional Training & Coaching",
      "Real Estate Services", 
      "R&D Services",
      "Security & Investigations", 
      "Staffing & Recruiting",
      "Translation & Interpretation Services"
    ],
    "Design": [
    "Design (Select All)",
      "Graphic Design",
      "Web Design", 
      "Interior Design",
      "Fashion Design", 
      "Industrial Design",
      "Architecture", 
      "Landscape Design",
      "Motion Graphics Design", 
      "Game Design",
      "Environmental Graphic Design", 
      "UX/UI Design",
      "Automotive Design", 
      "Jewelry Design",
      "Textile Design", 
      "Packaging Design",
      "Illustration", 
      "Animation & 3D Design",
      "Furniture Design", 
      "Exhibition Design",
      "Lighting Design", 
      "Sound Design",
      "Typeface Design", 
      "Service Design",
      "Sustainable/Green Design", 
      "Toy Design"
    ],
    "Education": [
    "Education (Select All)",
      "Education Management",
      "E-Learning", 
      "Early Childhood Education",
      "Primary/Secondary Education", 
      "Higher Education",
      "Research", 
      "Continuing Education",
      "Special Education", 
      "Professional Education",
      "Language Education", 
      "Educational Support Services",
      "Extracurricular Education", 
      "Environmental Education",
      "Health & Sex Education", 
      "Corporate Training",
      "Religious Education"
    ],
    "Energy & Mining": [
    "Energy & Mining (Select All)",
      "Oil & Gas Exploration & Production",
      "Oil & Gas Refining & Marketing", 
      "Renewable Energy",
      "Nuclear Power", 
      "Electricity Generation & Distribution",
      "Alternative Energy Sources", 
      "Energy Equipment & Services",
      "Metal Mining", 
      "Non-Metallic Mineral Mining",
      "Coal Mining", 
      "Mining Support Activities",
      "Specialized Mining", 
      "Mining Equipment & Technology",
      "Mining & Metals Processing"
    ],
    "Entertainment": [
    "Entertainment (Select All)",
      "Film & Movies",
      "Television", 
      "Music",
      "Video Games", 
      "Publishing",
      "Sports Entertainment", 
      "Visual Arts & Exhibitions",
      "Digital & Online Media", 
      "Themed Entertainment",
      "Events & Live Entertainment", 
      "Comedy & Variety Entertainment",
      "Radio & Audio Entertainment", 
      "Animation",
      "Cultural & Heritage Entertainment", 
      "Fashion & Lifestyle Entertainment",
      "VR & AR Entertainment", 
      "Literary Entertainment"
    ],
    "Finance": [
    "Finance (Select All)",
      "Banking", 
      "Investment",
      "Insurance", 
      "Financial Markets",
      "Wealth Management", 
      "Credit & Lending",
      "Payment Systems & Services", 
      "Fintech",
      "Financial Planning & Advisory", 
      "Finance Risk Management",
      "Regulatory Bodies & Organizations", 
      "Accounting & Auditing",
      "Real Estate Finance", 
      "Securities Brokerage & Trading",
      "Leasing & Equipment Finance", 
      "Pension Funds & Retirement Plans"
    ],
    "Health Care": [
    "Health Care (Select All)",
      "Hospitals", 
      "Medical Practices",
      "Nursing & Residential Care", 
      "Home Health Care",
      "Medical & Diagnostic Labs", 
      "Pharmaceuticals",
      "Biotechnology", 
      "Medical Devices",
      "Health Insurance", 
      "Mental Health Care",
      "Public Health", 
      "Alternative Medicine",
      "Dental", 
      "Vision Care",
      "Rehabilitation", 
      "Ambulatory Care",
      "Veterinary", 
      "Medical R&D",
      "Healthcare Technology", 
      "Healthcare Consulting & Management",
      "Nutrition & Weight Loss", 
      "Medical Education & Training",
      "Healthcare Support Services", 
      "Telemedicine"
    ],
    "Legal": [
    "Legal (Select All)",
      "Corporate Law", 
      "Criminal Law",
      "Civil Litigation", 
      "Family Law",
      "Estate Planning & Probate Law", 
      "Intellectual Property Law",
      "Real Estate Law", 
      "Tax Law",
      "Employment & Labor Law", 
      "Environmental Law",
      "International Law", 
      "Healthcare Law",
      "Bankruptcy Law", 
      "Immigration Law",
      "Maritime Law", 
      "Sports & Entertainment Law",
      "Consumer Law", 
      "Education Law",
      "Insurance Law", 
      "Administrative Law",
      "Antitrust Law", 
      "Telecommunications Law",
      "Human Rights Law", 
      "Media Law",
      "E-Commerce Law"
    ],
    "Manufacturing": [
    "Manufacturing (Select All)",
      "Automotive Manufacturing", 
      "Aerospace Manufacturing",
      "Chemical Manufacturing", 
      "Electronics Manufacturing",
      "Food & Beverage Manufacturing", 
      "Machinery Manufacturing",
      "Textile Manufacturing", 
      "Furniture Manufacturing",
      "Paper Manufacturing", 
      "Plastic & Rubber Manufacturing",
      "Metal Manufacturing", 
      "Medical Device Manufacturing",
      "Shipbuilding & Repair", 
      "Railroad Rolling Stock Manufacturing",
      "Defense Manufacturing", 
      "Energy Equipment Manufacturing",
      "Consumer Goods Manufacturing", 
      "Heavy Machinery Manufacturing",
      "Glass & Ceramic Manufacturing", 
      "Printing & Publishing",
      "Petroleum & Coal Products Manufacturing", 
      "Leather & Allied Product Manufacturing",
      "Nonmetallic Mineral Product Manufacturing", 
      "Wood Product Manufacturing",
      "Computer & Peripheral Equipment Manufacturing", 
      "Electrical Equipment, Appliance & Component Manufacturing",
      "Apparel Manufacturing", 
      "Tobacco Manufacturing",
      "Jewelry & Silverware Manufacturing", 
      "Sporting & Athletic Goods Manufacturing"
    ],
    "Media & Communications": [
    "Media & Communications (Select All)",
      "Broadcasting", 
      "Publishing",
      "Film & Entertainment", 
      "Digital Media",
      "Telecommunications", 
      "Music Industry",
      "Advertising & Marketing", 
      "Gaming & Interactive Entertainment",
      "Media Information Services", 
      "Media Technology",
      "Events & Conferences", 
      "Media Retail",
      "Media Education & Training", 
      "Media Regulation"
    ],
    "Nonprofit": [
    "Nonprofit (Select All)",
      "Healthcare and Medical Research", 
      "Education and Research",
      "Libraries", 
      "Social Services",
      "Environment & Wildlife", 
      "Arts, Culture & Humanities",
      "Nonprofit Organization Management", 
      "Community and Economic Development",
      "Religious Institutions", 
      "International Affairs & Development",
      "Civic & Social Organization", 
      "Voluntary & Membership Organizations",
      "Philanthropy", 
      "Fundraising",
      "Animal Welfare", 
      "Science & Technology Research",
      "Health & Wellness Promotion", 
      "Disaster Relief & Humanitarian Aid",
      "Youth Development & Services", 
      "Public Policy and Advocacy",
      "Sports, Recreation & Leisure", 
      "Public Broadcasting & Media",
      "Special Interest & Advocacy", 
      "Veterans & Military Support"
    ],
    "Public Administration": [
    "Public Administration (Select All)",
      "Legislative Functions", 
      "Executive Office",
      "Public Finance Management", 
      "Government Administration",
      "Government Relations", 
      "International Affairs",
      "Judiciary", 
      "Legislative Office",
      "Political Organization", 
      "Public Policy",
      "Defense & Civil Protection", 
      "Public Order, Safety & Justice",
      "Foreign Affairs", 
      "Public Health Administration",
      "Education Administration", 
      "Social Services Administration",
      "Environment & Wildlife Administration", 
      "Housing & Community Development",
      "Environmental Management & Protection", 
      "Transportation Administration",
      "Economic & Labor Affairs Administration", 
      "Cultural, Recreational & Religious Affairs",
      "Urban & Regional Planning", 
      "Emergency Services & Management",
      "Public Utilities Regulation", 
      "Veterans' Affairs & Services",
      "Regulatory Agencies", 
      "Government R&D",
      "Census & Population Statistics", 
      "Government Communications & PR"
    ],
    "Public Safety": [
    "Public Safety (Select All)",
      "Law Enforcement", 
      "Military",
      "Fire Services", 
      "Emergency Medical Services (EMS)",
      "Emergency Management", 
      "Public Safety Communications",
      "Homeland Security", 
      "Corrections & Rehabilitation",
      "Judicial & Legal Services", 
      "Search & Rescue Operations",
      "Public Health & Safety", 
      "Animal Control & Welfare",
      "Traffic & Road Safety", 
      "Public Safety Training & Education",
      "Public Safety R&D", 
      "Public Safety Community Services & Support"
    ],
    "Real Estate": [
    "Real Estate (Select All)",
      "Residential Real Estate", 
      "Commercial Real Estate",
      "Industrial Real Estate", 
      "Land Development",
      "Real Estate Investing", 
      "Property Management",
      "Real Estate Brokerage & Sales", 
      "Real Estate Financing",
      "Architecture & Design", 
      "Real Estate Appraisal & Valuation",
      "Real Estate Marketing & Advertising", 
      "Real Estate Legal Services",
      "Real Estate Consulting", 
      "Sustainable Real Estate",
      "Real Estate Technology", 
      "Vacation & Short-term Rentals",
      "Senior & Assisted Living Real Estate", 
      "Student Housing",
      "Agricultural Real Estate", 
      "Historic Property Real Estate",
      "Foreclosure & Distressed Properties", 
      "Luxury Real Estate"
    ],
    "Recreation & Travel": [
    "Recreation & Travel (Select All)",
      "Tourism", 
      "Hospitality",
      "Travel Services", 
      "Transportation for Travel",
      "Attractions & Entertainment", 
      "Outdoor Recreation",
      "Recreational Products & Equipment", 
      "Wellness & Spa",
      "Food & Beverage", 
      "Travel Technology",
      "Specialty Travel", 
      "Travel Media & Publications",
      "Travel Insurance & Safety", 
      "Education & Training in Travel & Recreation",
      "Travel Regulation", 
      "Travel R&C",
      "Travel Ancillary Services"
    ],
    "Retail & Wholesale": [
    "Retail & Wholesale (Select All)",
      "Grocery Stores", 
      "Supermarkets",
      "Health & Personal Care Stores", 
      "Clothing & Apparel Stores",
      "Electronics & Appliance Stores", 
      "Furniture & Home Furnishings Stores",
      "Sporting Goods, Hobby, Book & Music Stores", 
      "General Merchandise Stores",
      "Online Retail", 
      "Specialty Retail",
      "Wholesale"
    ],
    "Tech Software & IT Services": [
    "Tech Software & IT Services (Select All)",
      "Software Development & Engineering", 
      "IT Services",
      "Cloud Technologies", 
      "Cybersecurity",
      "AI & ML", 
      "Data Management & Analytics",
      "Internet of Things (IoT)", 
      "E-Commerce & Internet Services",
      "Enterprise Software & Solutions", 
      "Networking & Communications",
      "Hardware & Equipment", 
      "Emerging Technologies",
      "Web3/Crypto", 
      "Digital Media & Entertainment",
      "Educational Technology (EdTech)", 
      "Health Information Technology",
      "Legal & Compliance Technology", 
      "Retail & Point of Sale Technology",
      "Energy & Utilities Technology", 
      "Real Estate Technology"
    ],
    "Transportation & Logistics": [
    "Transportation & Logistics (Select All)",
      "Air Transportation", 
      "Rail Transportation",
      "Road Transportation", 
      "Maritime & Water Transportation",
      "Logistics & Supply Chain", 
      "Postal Services",
      "Pipeline Transportation", 
      "Support Services & Infrastructure",
      "Specialized Transportation Services", 
      "Intermodal & Multimodal Transportation",
      "Transportation Consulting & Services", 
      "Emerging Transportation Technologies"
    ],
    "Wellness & Fitness": [
    "Wellness & Fitness (Select All)",
      "Fitness Centers & Gyms", 
      "Personal Training & Coaching",
      "Nutrition & Dietetics", 
      "Health & Wellness Retreats",
      "Yoga & Pilates Studios", 
      "Physical Therapy & Rehabilitation",
      "Sports Training", 
      "Mental Wellness Programs",
      "Wellness Apps & Digital Platforms", 
      "Corporate Wellness Programs",
      "Alternative Therapies", 
      "Fitness & Wellness Equipment",
      "Supplements & Nutraceuticals", 
      "Sporting Goods & Retail",
      "Wellness Tourism", 
      "Health Clubs & Community Centers",
      "Online Fitness & Wellness Courses", 
      "Health & Wellness Consulting",
      "Fitness & Wellness Events & Expositions", 
      "Wellness Publications & Media"
    ]
  };


  export {Industries,industriesSubcategories};
  
 
  