// jobCategories.js
export const jobCategories = [
    "Accounting and Finance",
    "Administrative and Office Support",
    "Advertising, Marketing, and Public Relations",
    "Agriculture and Forestry",
    "Architecture and Engineering",
    "Arts, Culture, and Entertainment",
    "Construction and Trades",
    "Customer Service",
    "Data and Analytics",
    "Education and Training",
    "Energy and Utilities",
    "Food Services and Hospitality",
    "Government and Public Administration",
    "Healthcare and Medicine",
    "Human Resources",
    "Information Technology (IT) and Software Development",
    "Legal and Compliance",
    "Logistics and Supply Chain",
    "Manufacturing and Production",
    "Media and Communication",
    "Nonprofit and Charity",
    "Real Estate",
    "Research and Development",
    "Retail and Sales",
    "Science and Biotechnology",
    "Security and Law Enforcement",
    "Skilled Trades",
    "Sports and Recreation",
    "Transportation and Warehousing",
    "Travel and Tourism",
    "Writing and Editing"
  ];
  