// jobCategories.js
export const jobCategories = [
   'Accounting Payroll & Financial Planning Jobs',
  'Administration Jobs',
  'Arts and Design Jobs',
  'Business Development Jobs',
  'Business Operations & Strategy Jobs',
  'Chief of Staff Jobs',
  'Community and Social Services Jobs',
  'Content Design Jobs',
  'Content Marketing Jobs',
  'Consulting Jobs',
  'Copywriter Jobs',
  'Customer Success & Support Jobs',
  'Data Analyst Jobs',
  'Data Engineer Jobs',
  'Data Scientist Jobs',
  'DevOps & Production Engineering Jobs',
  'Education Jobs',
  'Engineering Manager Jobs',
  'Engineering Jobs',
  'Entrepreneurship Jobs',
  'Executive Assistant Jobs',
  'Finance Jobs',
  'Growth Marketing Jobs',
  'Hardware Engineer Jobs',
  'Healthcare Services Jobs',
  'Human Resources Jobs',
  'Infrastructure Engineer Jobs',
  'Information Technology Jobs',
  'IT Support Jobs',
  'Legal Jobs',
  'Machine Learning Engineer Jobs',
  'Marketing Jobs',
  'Media and Communication Jobs',
  'Military and Protective Services Jobs',
  'Operations Jobs',
  'Product Analyst Jobs',
  'Performance Marketing Jobs',
  'Product Designer Jobs',
  'Product Manager Jobs',
  'Project & Program Management Jobs',
  'Product Marketing Jobs',
  'Purchasing Jobs',
  'Marketing (General) Jobs',
  'QA Engineer (Quality Assurance) Jobs',
  'Quality Assurance Jobs',
  'Real Estate Jobs',
  'Research Jobs',
  'Recruitment Jobs',
  'Risk & Compliance Jobs',
  'SEO Marketing Jobs',
  'Sales Jobs',
  'Security Engineer Jobs',
  'Social Media & Community Jobs',
  'Software Engineer Jobs',
  'Solutions Engineer Jobs',
  'Support Engineer Jobs',
  'Support Jobs',
  'Technical Writer Jobs',
  'Technical Product Manager Jobs',
  'UX Researcher Jobs'
  ];
  