const countryData = [
  { country: "Africa", emoji: "🦁", index: 0, type: "region" },
  { country: "Asia", emoji: "⛩", index: 1, type: "region" },
  { country: "Europe", emoji: "🇪🇺", index: 2, type: "region" },
  { country: "Latin America", emoji: "💃", index: 3, type: "region" },
  { country: "Middle East", emoji: "🕌", index: 4, type: "region" },
  { country: "North America", emoji: "🏈", index: 5, type: "region" },
  { country: "Oceania", emoji: "🌊", index: 6, type: "region" },
  { country: "Worldwide", emoji: "🌏", index: 7, type: "region" },
  { country: "Afghanistan", emoji: "🇦🇫", index: 8, type: "country" },
  { country: "Albania", emoji: "🇦🇱", index: 9, type: "country" },
  { country: "Algeria", emoji: "🇩🇿", index: 10, type: "country" },
  { country: "American Samoa", emoji: "🇦🇸", index: 11, type: "country" },
  { country: "Andorra", emoji: "🇦🇩", index: 12, type: "country" },
  { country: "Angola", emoji: "🇦🇴", index: 13, type: "country" },
  { country: "Anguilla", emoji: "🇦🇮", index: 14, type: "country" },
  { country: "Antarctica", emoji: "🇦🇶", index: 15, type: "region" },
  { country: "Antigua and Barbuda", emoji: "🇦🇬", index: 16, type: "country" },
  { country: "Argentina", emoji: "🇦🇷", index: 17, type: "country" },
  { country: "Armenia", emoji: "🇦🇲", index: 18, type: "country" },
  { country: "Aruba", emoji: "🇦🇼", index: 19, type: "country" },
  { country: "Australia", emoji: "🇦🇺", index: 20, type: "country" },
  { country: "Austria", emoji: "🇦🇹", index: 21, type: "country" },
  { country: "Azerbaijan", emoji: "🇦🇿", index: 22, type: "country" },
  { country: "Bahamas", emoji: "🇧🇸", index: 23, type: "country" },
  { country: "Bahrain", emoji: "🇧🇭", index: 24, type: "country" },
  { country: "Bangladesh", emoji: "🇧🇩", index: 25, type: "country" },
  { country: "Barbados", emoji: "🇧🇧", index: 26, type: "country" },
  { country: "Belarus", emoji: "🇧🇾", index: 27, type: "country" },
  { country: "Bermuda", emoji: "🇧🇲", index: 28, type: "country" },
  { country: "Bhutan", emoji: "🇧🇹", index: 29, type: "country" },
  { country: "Bolivia", emoji: "🇧🇴", index: 30, type: "country" },
  {
    country: "Bosnia and Herzegovina",
    emoji: "🇧🇦",
    index: 31,
    type: "country",
  },
  { country: "Botswana", emoji: "🇧🇼", index: 32, type: "country" },
  { country: "Bouvet Island", emoji: "🇧🇻", index: 33, type: "country" },
  { country: "Brazil", emoji: "🇧🇷", index: 34, type: "country" },
  {
    country: "British Indian Ocean country",
    emoji: "🇮🇴",
    index: 35,
    type: "country",
  },
  {
    country: "British Virgin Islands",
    emoji: "🇻🇬",
    index: 36,
    type: "country",
  },
  { country: "Bulgaria", emoji: "🇧🇬", index: 37, type: "country" },
  { country: "Burkina Faso", emoji: "🇧🇫", index: 38, type: "country" },
  { country: "Cambodia", emoji: "🇰🇭", index: 39, type: "country" },
  { country: "Cameroon", emoji: "🇨🇲", index: 40, type: "country" },
  { country: "Canada", emoji: "🇨🇦", index: 41, type: "country" },
  { country: "Cape Verde", emoji: "🇨🇻", index: 42, type: "country" },
  { country: "Cayman Islands", emoji: "🇰🇾", index: 43, type: "country" },
  {
    country: "Central African Republic",
    emoji: "🇨🇫",
    index: 44,
    type: "country",
  },
  { country: "Chad", emoji: "🇹🇩", index: 45, type: "country" },
  { country: "China", emoji: "🇨🇳", index: 46, type: "country" },
  { country: "Christmas Island", emoji: "🇨🇽", index: 47, type: "country" },
  { country: "Cocos Islands", emoji: "🇨🇨", index: 48, type: "country" },
  { country: "Colombia", emoji: "🇨🇴", index: 49, type: "country" },
  { country: "Cook Islands", emoji: "🇨🇰", index: 50, type: "country" },
  { country: "Costa Rica", emoji: "🇨🇷", index: 51, type: "country" },
  { country: "Croatia", emoji: "🇭🇷", index: 52, type: "country" },
  { country: "Cuba", emoji: "🇨🇺", index: 53, type: "country" },
  { country: "Curacao", emoji: "🇨🇼", index: 54, type: "country" },
  {
    country: "Democratic Republic of the Congo",
    emoji: "🇨🇩",
    index: 55,
    type: "country",
  },
  { country: "Denmark", emoji: "🇩🇰", index: 56, type: "country" },
  { country: "Dominica", emoji: "🇩🇲", index: 57, type: "country" },
  { country: "Dominican Republic", emoji: "🇩🇴", index: 58, type: "country" },
  { country: "East Timor", emoji: "🇹🇱", index: 59, type: "country" },
  { country: "Ecuador", emoji: "🇪🇨", index: 60, type: "country" },
  { country: "El Salvador", emoji: "🇸🇻", index: 61, type: "country" },
  { country: "Equatorial Guinea", emoji: "🇬🇶", index: 62, type: "country" },
  { country: "Eritrea", emoji: "🇪🇷", index: 63, type: "country" },
  { country: "Estonia", emoji: "🇪🇪", index: 64, type: "country" },
  { country: "Ethiopia", emoji: "🇪🇹", index: 65, type: "country" },
  { country: "Falkland Islands", emoji: "🇫🇰", index: 66, type: "country" },
  { country: "Faroe Islands", emoji: "🇫🇴", index: 67, type: "country" },
  { country: "Finland", emoji: "🇫🇮", index: 68, type: "country" },
  { country: "France", emoji: "🇫🇷", index: 69, type: "country" },
  { country: "French Polynesia", emoji: "🇵🇫", index: 70, type: "country" },
  { country: "Gabon", emoji: "🇬🇦", index: 71, type: "country" },
  { country: "Gambia", emoji: "🇬🇲", index: 72, type: "country" },
  { country: "Georgia", emoji: "🇬🇪", index: 73, type: "country" },
  { country: "Germany", emoji: "🇩🇪", index: 74, type: "country" },
  { country: "Ghana", emoji: "🇬🇭", index: 75, type: "country" },
  { country: "Gibraltar", emoji: "🇬🇮", index: 76, type: "country" },
  { country: "Greenland", emoji: "🇬🇱", index: 77, type: "country" },
  { country: "Grenada", emoji: "🇬🇩", index: 78, type: "country" },
  { country: "Guam", emoji: "🇬🇺", index: 79, type: "country" },
  { country: "Guatemala", emoji: "🇬🇹", index: 80, type: "country" },
  { country: "Guinea", emoji: "🇬🇳", index: 81, type: "country" },
  { country: "Guinea-Bissau", emoji: "🇬🇼", index: 82, type: "country" },
  { country: "Bissau", emoji: "🇬🇼", index: 83, type: "region" },
  { country: "Guyana", emoji: "🇬🇾", index: 84, type: "country" },
  { country: "Haiti", emoji: "🇭🇹", index: 85, type: "country" },
  {
    country: "Heard Island and McDonald Islands",
    emoji: "🇭🇲",
    index: 86,
    type: "country",
  },
  { country: "Honduras", emoji: "🇭🇳", index: 87, type: "country" },
  { country: "Hungary", emoji: "🇭🇺", index: 88, type: "country" },
  { country: "Iceland", emoji: "🇮🇸", index: 89, type: "country" },
  { country: "India", emoji: "🇮🇳", index: 90, type: "country" },
  { country: "Indonesia", emoji: "🇮🇩", index: 91, type: "country" },
  { country: "Iran", emoji: "🇮🇷", index: 92, type: "country" },
  { country: "Iraq", emoji: "🇮🇶", index: 93, type: "country" },
  { country: "Ireland", emoji: "🇮🇪", index: 94, type: "country" },
  { country: "Isle of Man", emoji: "🇮🇲", index: 95, type: "country" },
  { country: "Israel", emoji: "🇮🇱", index: 96, type: "country" },
  { country: "Italy", emoji: "🇮🇹", index: 97, type: "country" },
  { country: "Ivory Coast", emoji: "🇨🇮", index: 98, type: "country" },
  { country: "Jamaica", emoji: "🇯🇲", index: 99, type: "country" },
  { country: "Japan", emoji: "🇯🇵", index: 100, type: "country" },
  { country: "Jordan", emoji: "🇯🇴", index: 101, type: "country" },
  { country: "Kazakhstan", emoji: "🇰🇿", index: 102, type: "country" },
  { country: "Kenya", emoji: "🇰🇪", index: 103, type: "country" },
  { country: "Kiribati", emoji: "🇰🇮", index: 104, type: "country" },
  { country: "Kuwait", emoji: "🇰🇼", index: 105, type: "country" },
  { country: "Kyrgyzstan", emoji: "🇰🇬", index: 106, type: "country" },
  { country: "Laos", emoji: "🇱🇦", index: 107, type: "country" },
  { country: "Latvia", emoji: "🇱🇻", index: 108, type: "country" },
  { country: "Lebanon", emoji: "🇱🇧", index: 109, type: "country" },
  { country: "Liberia", emoji: "🇱🇷", index: 110, type: "country" },
  { country: "Libya", emoji: "🇱🇾", index: 111, type: "country" },
  { country: "Lithuania", emoji: "🇱🇹", index: 112, type: "country" },
  { country: "Macau", emoji: "🇲🇴", index: 113, type: "country" },
  { country: "Macedonia", emoji: "🇲🇰", index: 114, type: "country" },
  { country: "Madagascar", emoji: "🇲🇬", index: 115, type: "country" },
  { country: "Malawi", emoji: "🇲🇼", index: 116, type: "country" },
  { country: "Malaysia", emoji: "🇲🇾", index: 117, type: "country" },
  { country: "Maldives", emoji: "🇲🇻", index: 118, type: "country" },
  { country: "Mali", emoji: "🇲🇱", index: 119, type: "country" },
  { country: "Malta", emoji: "🇲🇹", index: 120, type: "country" },
  { country: "Marshall Islands", emoji: "🇲🇭", index: 121, type: "country" },
  { country: "Mauritania", emoji: "🇲🇷", index: 122, type: "country" },
  { country: "Mauritius", emoji: "🇲🇺", index: 123, type: "country" },
  { country: "Mayotte", emoji: "🇾🇹", index: 124, type: "country" },
  { country: "Micronesia", emoji: "🇫🇲", index: 125, type: "country" },
  { country: "Moldova", emoji: "🇲🇩", index: 126, type: "country" },
  { country: "Monaco", emoji: "🇲🇨", index: 127, type: "country" },
  { country: "Mongolia", emoji: "🇲🇳", index: 128, type: "country" },
  { country: "Montserrat", emoji: "🇲🇸", index: 129, type: "country" },
  { country: "Mozambique", emoji: "🇲🇿", index: 130, type: "country" },
  { country: "Myanmar", emoji: "🇲🇲", index: 131, type: "country" },
  { country: "Namibia", emoji: "🇳🇦", index: 132, type: "country" },
  { country: "Nauru", emoji: "🇳🇷", index: 133, type: "country" },
  { country: "Nepal", emoji: "🇳🇵", index: 134, type: "country" },
  { country: "Netherlands", emoji: "🇳🇱", index: 135, type: "country" },
  {
    country: "Netherlands Antilles",
    emoji: "🇧🇶",
    index: 136,
    type: "country",
  },
  { country: "New Caledonia", emoji: "🇳🇨", index: 137, type: "country" },
  { country: "New Zealand", emoji: "🇳🇿", index: 138, type: "country" },
  { country: "Nicaragua", emoji: "🇳🇮", index: 139, type: "country" },
  { country: "Nigeria", emoji: "🇳🇬", index: 140, type: "country" },
  { country: "Norfolk Island", emoji: "🇳🇫", index: 141, type: "country" },
  { country: "North Korea", emoji: "🇰🇵", index: 142, type: "country" },
  {
    country: "Northern Mariana Islands",
    emoji: "🇲🇵",
    index: 143,
    type: "country",
  },
  { country: "Norway", emoji: "🇳🇴", index: 144, type: "country" },
  { country: "Oman", emoji: "🇴🇲", index: 145, type: "country" },
  { country: "Pakistan", emoji: "🇵🇰", index: 146, type: "country" },
  { country: "Palau", emoji: "🇵🇼", index: 147, type: "country" },
  { country: "Palestine", emoji: "🇵🇸", index: 148, type: "country" },
  { country: "Panama", emoji: "🇵🇦", index: 149, type: "country" },
  { country: "Papua New Guinea", emoji: "🇵🇬", index: 150, type: "country" },
  { country: "Paraguay", emoji: "🇵🇾", index: 151, type: "country" },
  { country: "Pitcairn", emoji: "🇵🇳", index: 152, type: "country" },
  { country: "Poland", emoji: "🇵🇱", index: 153, type: "country" },
  { country: "Portugal", emoji: "🇵🇹", index: 154, type: "country" },
  { country: "Qatar", emoji: "🇶🇦", index: 155, type: "country" },
  { country: "Romania", emoji: "🇷🇴", index: 156, type: "country" },
  { country: "Russia", emoji: "🇷🇺", index: 157, type: "country" },
  { country: "Rwanda", emoji: "🇷🇼", index: 158, type: "country" },
  { country: "Saint Barthelemy", emoji: "🇧🇱", index: 159, type: "country" },
  { country: "Saint Helena", emoji: "🇸🇭", index: 160, type: "country" },
  {
    country: "Saint Kitts and Nevis",
    emoji: "🇰🇳",
    index: 161,
    type: "country",
  },
  { country: "Saint Lucia", emoji: "🇱🇨", index: 162, type: "country" },
  { country: "Saint Martin", emoji: "🇲🇫", index: 163, type: "country" },
  {
    country: "Saint Pierre and Miquelon",
    emoji: "🇵🇲",
    index: 164,
    type: "country",
  },
  {
    country: "Saint Vincent and the Grenadines",
    emoji: "🇻🇨",
    index: 165,
    type: "country",
  },
  { country: "Samoa", emoji: "🇼🇸", index: 166, type: "country" },
  { country: "San Marino", emoji: "🇸🇲", index: 167, type: "country" },
  {
    country: "Sao Tome and Principe",
    emoji: "🇸🇹",
    index: 168,
    type: "country",
  },
  { country: "Saudi Arabia", emoji: "🇸🇦", index: 169, type: "country" },
  { country: "Senegal", emoji: "🇸🇳", index: 170, type: "country" },
  { country: "Serbia", emoji: "🇷🇸", index: 171, type: "country" },
  { country: "Sierra Leone", emoji: "🇸🇱", index: 172, type: "country" },
  { country: "Singapore", emoji: "🇸🇬", index: 173, type: "country" },
  { country: "Sint Maarten", emoji: "🇸🇽", index: 174, type: "country" },
  { country: "Slovakia", emoji: "🇸🇰", index: 175, type: "country" },
  { country: "Slovenia", emoji: "🇸🇮", index: 176, type: "country" },
  { country: "Solomon Islands", emoji: "🇸🇧", index: 177, type: "country" },
  { country: "Somalia", emoji: "🇸🇴", index: 178, type: "country" },
  { country: "South Africa", emoji: "🇿🇦", index: 179, type: "country" },
  {
    country: "South Georgia and the South Sandwich Islands",
    emoji: "🇬🇸",
    index: 180,
    type: "country",
  },
  { country: "South Korea", emoji: "🇰🇷", index: 181, type: "country" },
  { country: "South Sudan", emoji: "🇸🇸", index: 182, type: "country" },
  { country: "Spain", emoji: "🇪🇸", index: 183, type: "country" },
  { country: "Sri Lanka", emoji: "🇱🇰", index: 184, type: "country" },
  { country: "Sudan", emoji: "🇸🇩", index: 185, type: "country" },
  { country: "Suriname", emoji: "🇸🇷", index: 186, type: "country" },
  {
    country: "Svalbard and Jan Mayen",
    emoji: "🇸🇯",
    index: 187,
    type: "country",
  },
  { country: "Swaziland", emoji: "🇸🇿", index: 188, type: "country" },
  { country: "Switzerland", emoji: "🇨🇭", index: 189, type: "country" },
  { country: "Syria", emoji: "🇸🇾", index: 190, type: "country" },
  { country: "Taiwan", emoji: "🇹🇼", index: 191, type: "country" },
  { country: "Tajikistan", emoji: "🇹🇯", index: 192, type: "country" },
  { country: "Tanzania", emoji: "🇹🇿", index: 193, type: "country" },
  { country: "Thailand", emoji: "🇹🇭", index: 194, type: "country" },
  { country: "Tokelau", emoji: "🇹🇰", index: 195, type: "country" },
  { country: "Tonga", emoji: "🇹🇴", index: 196, type: "country" },
  { country: "Trinidad and Tobago", emoji: "🇹🇹", index: 197, type: "country" },
  { country: "Tunisia", emoji: "🇹🇳", index: 198, type: "country" },
  { country: "Turkmenistan", emoji: "🇹🇲", index: 199, type: "country" },
  {
    country: "Turks and Caicos Islands",
    emoji: "🇹🇨",
    index: 200,
    type: "country",
  },
  { country: "Tuvalu", emoji: "🇹🇻", index: 201, type: "country" },
  {
    country: "U.S. Virgin Islands",
    emoji: "🇻🇮",
    index: 202,
    type: "country",
  },
  { country: "Uganda", emoji: "🇺🇬", index: 203, type: "country" },
  { country: "Ukraine", emoji: "🇺🇦", index: 204, type: "country" },
  { country: "United Arab Emirates", emoji: "🇦🇪", index: 205, type: "country" },
  { country: "United States", emoji: "🇺🇸", index: 206, type: "country" },
  { country: "Los Angeles", emoji: "🇺🇸", index: 207, type: "city" },
  { country: "Chicago", emoji: "🇺🇸", index: 208, type: "city" },
  { country: "Philadelphia", emoji: "🇺🇸", index: 209, type: "city" },
  { country: "San Antonio", emoji: "🇺🇸", index: 210, type: "city" },
  { country: "San Diego", emoji: "🇺🇸", index: 211, type: "city" },
  { country: "Dallas", emoji: "🇺🇸", index: 212, type: "city" },
  { country: "San Jose", emoji: "🇺🇸", index: 213, type: "city" },
  { country: "San Diego Metro Area", emoji: "🇺🇸", index: 214, type: "region" },
  { country: "Austin", emoji: "🇺🇸", index: 215, type: "city" },
  { country: "Jacksonville", emoji: "🇺🇸", index: 216, type: "city" },
  { country: "San Francisco", emoji: "🇺🇸", index: 217, type: "city" },
  { country: "Charlotte", emoji: "🇺🇸", index: 218, type: "city" },
  { country: "Indianapolis", emoji: "🇺🇸", index: 219, type: "city" },
  { country: "Seattle", emoji: "🇺🇸", index: 220, type: "city" },
  { country: "Nashville", emoji: "🇺🇸", index: 221, type: "city" },
  { country: "El Paso", emoji: "🇺🇸", index: 222, type: "city" },
  { country: "Portland", emoji: "🇺🇸", index: 223, type: "city" },
  { country: "Oklahoma City", emoji: "🇺🇸", index: 224, type: "city" },
  { country: "Las Vegas", emoji: "🇺🇸", index: 225, type: "city" },
  { country: "Baltimore", emoji: "🇺🇸", index: 226, type: "city" },
  { country: "Milwaukee", emoji: "🇺🇸", index: 227, type: "city" },
  { country: "Albuquerque", emoji: "🇺🇸", index: 228, type: "city" },
  { country: "Sacramento", emoji: "🇺🇸", index: 229, type: "city" },
  { country: "Mesa", emoji: "🇺🇸", index: 230, type: "city" },
  { country: "Atlanta", emoji: "🇺🇸", index: 231, type: "city" },
  { country: "Kansas City", emoji: "🇺🇸", index: 232, type: "city" },
  { country: "Colorado Springs", emoji: "🇺🇸", index: 233, type: "city" },
  { country: "Miami", emoji: "🇺🇸", index: 234, type: "city" },
  { country: "Raleigh", emoji: "🇺🇸", index: 235, type: "city" },
  { country: "Omaha", emoji: "🇺🇸", index: 236, type: "city" },
  { country: "Long Beach", emoji: "🇺🇸", index: 237, type: "city" },
  { country: "Virginia Beach", emoji: "🇺🇸", index: 238, type: "city" },
  { country: "Oakland", emoji: "🇺🇸", index: 239, type: "city" },
  { country: "Minneapolis", emoji: "🇺🇸", index: 240, type: "city" },
  { country: "Tulsa", emoji: "🇺🇸", index: 241, type: "city" },
  { country: "Wichita", emoji: "🇺🇸", index: 242, type: "city" },
  { country: "New Orleans", emoji: "🇺🇸", index: 243, type: "city" },
  { country: "Arlington", emoji: "🇺🇸", index: 244, type: "city" },
  { country: "Tampa", emoji: "🇺🇸", index: 245, type: "city" },
  { country: "Santa Ana", emoji: "🇺🇸", index: 246, type: "city" },
  { country: "Santa Clara", emoji: "🇺🇸", index: 247, type: "city" },
  { country: "Cincinnati", emoji: "🇺🇸", index: 248, type: "city" },
  { country: "Anchorage", emoji: "🇺🇸", index: 249, type: "city" },
  { country: "Saint Paul", emoji: "🇺🇸", index: 250, type: "city" },
  { country: "Newark", emoji: "🇺🇸", index: 251, type: "city" },
  { country: "Buffalo", emoji: "🇺🇸", index: 252, type: "city" },
  { country: "Plano", emoji: "🇺🇸", index: 253, type: "city" },
  { country: "Fort Wayne", emoji: "🇺🇸", index: 254, type: "city" },
  { country: "Chula Vista", emoji: "🇺🇸", index: 255, type: "city" },
  { country: "Orlando", emoji: "🇺🇸", index: 256, type: "city" },
  { country: "Chandler", emoji: "🇺🇸", index: 257, type: "city" },
  { country: "Laredo", emoji: "🇺🇸", index: 258, type: "city" },
  { country: "Madison", emoji: "🇺🇸", index: 259, type: "city" },
  { country: "Winston-Salem", emoji: "🇺🇸", index: 260, type: "city" },
  { country: "Baton Rouge", emoji: "🇺🇸", index: 261, type: "city" },
  { country: "Durham", emoji: "🇺🇸", index: 262, type: "city" },
  { country: "Garland", emoji: "🇺🇸", index: 263, type: "city" },
  { country: "Glendale", emoji: "🇺🇸", index: 264, type: "city" },
  { country: "California", emoji: "🇺🇸", index: 265, type: "state" },
  { country: "Hialeah", emoji: "🇺🇸", index: 266, type: "city" },
  { country: "Chesapeake", emoji: "🇺🇸", index: 267, type: "city" },
  { country: "Scottsdale", emoji: "🇺🇸", index: 268, type: "city" },
  { country: "North Las Vegas", emoji: "🇺🇸", index: 269, type: "city" },
  { country: "Fayetteville", emoji: "🇺🇸", index: 270, type: "city" },
  { country: "Birmingham", emoji: "🇺🇸", index: 271, type: "city" },
  { country: "Oxnard", emoji: "🇺🇸", index: 272, type: "city" },
  { country: "Fontana", emoji: "🇺🇸", index: 273, type: "city" },
  { country: "Moreno Valley", emoji: "🇺🇸", index: 274, type: "city" },
  { country: "Huntington Beach", emoji: "🇺🇸", index: 275, type: "city" },
  { country: "Aurora", emoji: "🇺🇸", index: 276, type: "city" },
  { country: "Grand Rapids", emoji: "🇺🇸", index: 277, type: "city" },
  { country: "Salt Lake City", emoji: "🇺🇸", index: 278, type: "city" },
  { country: "Amarillo", emoji: "🇺🇸", index: 279, type: "city" },
  { country: "Akron", emoji: "🇺🇸", index: 280, type: "city" },
  { country: "Augusta", emoji: "🇺🇸", index: 281, type: "city" },
  { country: "Syracuse", emoji: "🇺🇸", index: 282, type: "city" },
  { country: "Jackson", emoji: "🇺🇸", index: 283, type: "city" },
  { country: "Cape Coral", emoji: "🇺🇸", index: 284, type: "city" },
  { country: "Grand Prairie", emoji: "🇺🇸", index: 285, type: "city" },
  { country: "East Los Angeles", emoji: "🇺🇸", index: 286, type: "city" },
  { country: "Peoria", emoji: "🇺🇸", index: 287, type: "city" },
  { country: "Cary", emoji: "🇺🇸", index: 288, type: "city" },
  { country: "Corona", emoji: "🇺🇸", index: 289, type: "city" },
  { country: "Salinas", emoji: "🇺🇸", index: 290, type: "city" },
  { country: "Palmdale", emoji: "🇺🇸", index: 291, type: "city" },
  { country: "Pasadena", emoji: "🇺🇸", index: 292, type: "city" },
  { country: "Fort Lauderdale", emoji: "🇺🇸", index: 293, type: "city" },
  { country: "Hayward", emoji: "🇺🇸", index: 294, type: "city" },
  { country: "Pomona", emoji: "🇺🇸", index: 295, type: "city" },
  { country: "Paterson", emoji: "🇺🇸", index: 296, type: "city" },
  { country: "Alexandria", emoji: "🇺🇸", index: 297, type: "city" },
  { country: "Sunnyvale", emoji: "🇺🇸", index: 298, type: "city" },
  { country: "Lakewood", emoji: "🇺🇸", index: 299, type: "city" },
  { country: "Torrance", emoji: "🇺🇸", index: 300, type: "city" },
  { country: "Clarksville", emoji: "🇺🇸", index: 301, type: "city" },
  { country: "Naperville", emoji: "🇺🇸", index: 302, type: "city" },
  { country: "Savannah", emoji: "🇺🇸", index: 303, type: "city" },
  { country: "McAllen", emoji: "🇺🇸", index: 304, type: "city" },
  { country: "Lancaster", emoji: "🇺🇸", index: 305, type: "city" },
  { country: "West Valley City", emoji: "🇺🇸", index: 306, type: "city" },
  { country: "Columbia", emoji: "🇺🇸", index: 307, type: "city" },
  { country: "Abilene", emoji: "🇺🇸", index: 308, type: "city" },
  { country: "Ann Arbor", emoji: "🇺🇸", index: 309, type: "city" },
  { country: "Allentown", emoji: "🇺🇸", index: 310, type: "city" },
  { country: "Beaumont", emoji: "🇺🇸", index: 311, type: "city" },
  { country: "Norman", emoji: "🇺🇸", index: 312, type: "city" },
  { country: "Costa Mesa", emoji: "🇺🇸", index: 313, type: "city" },
  { country: "San Buenaventura", emoji: "🇺🇸", index: 314, type: "city" },
  { country: "Miami Gardens", emoji: "🇺🇸", index: 315, type: "city" },
  { country: "Carlsbad", emoji: "🇺🇸", index: 316, type: "city" },
  { country: "North Charleston", emoji: "🇺🇸", index: 317, type: "city" },
  { country: "Fairfield", emoji: "🇺🇸", index: 318, type: "city" },
  { country: "Lafayette", emoji: "🇺🇸", index: 319, type: "city" },
  { country: "Gresham", emoji: "🇺🇸", index: 320, type: "city" },
  { country: "Missoula", emoji: "🇺🇸", index: 321, type: "city" },
  { country: "Gary", emoji: "🇺🇸", index: 322, type: "city" },
  { country: "West Covina", emoji: "🇺🇸", index: 323, type: "city" },
  { country: "La Mesa", emoji: "🇺🇸", index: 324, type: "city" },
  { country: "New Braunfels", emoji: "🇺🇸", index: 325, type: "city" },
  { country: "El Cajon", emoji: "🇺🇸", index: 326, type: "city" },
  { country: "Waltham", emoji: "🇺🇸", index: 327, type: "city" },
  { country: "Farmington", emoji: "🇺🇸", index: 328, type: "city" },
  { country: "Kahului", emoji: "🇺🇸", index: 329, type: "city" },
  { country: "Davenport", emoji: "🇺🇸", index: 330, type: "city" },
  { country: "San Juan", emoji: "🇺🇸", index: 331, type: "city" },
  { country: "South Pasadena", emoji: "🇺🇸", index: 332, type: "city" },
  { country: "Novato", emoji: "🇺🇸", index: 333, type: "city" },
  { country: "Richland", emoji: "🇺🇸", index: 334, type: "city" },
  { country: "La Quinta", emoji: "🇺🇸", index: 335, type: "city" },
  { country: "Machesney Park", emoji: "🇺🇸", index: 336, type: "city" },
  { country: "Floral Park", emoji: "🇺🇸", index: 337, type: "city" },
  { country: "South San Francisco", emoji: "🇺🇸", index: 338, type: "city" },
  { country: "Waupun", emoji: "🇺🇸", index: 339, type: "city" },
  { country: "Pleasant Grove", emoji: "🇺🇸", index: 340, type: "city" },
  { country: "Barnstable Town", emoji: "🇺🇸", index: 341, type: "city" },
  { country: "San Rafael", emoji: "🇺🇸", index: 342, type: "city" },
  { country: "Sun Village", emoji: "🇺🇸", index: 343, type: "city" },
  { country: "Rancho San Diego", emoji: "🇺🇸", index: 344, type: "city" },
  { country: "Falls Church", emoji: "🇺🇸", index: 345, type: "city" },
  { country: "North Adams", emoji: "🇺🇸", index: 346, type: "city" },
  { country: "Sallisaw", emoji: "🇺🇸", index: 347, type: "city" },
  { country: "Anaheim", emoji: "🇺🇸", index: 348, type: "city" },
  { country: "Palm Desert", emoji: "🇺🇸", index: 349, type: "city" },
  { country: "Lake Charles", emoji: "🇺🇸", index: 350, type: "city" },
  { country: "North Tonawanda", emoji: "🇺🇸", index: 351, type: "city" },
  { country: "Hastings", emoji: "🇺🇸", index: 352, type: "city" },
  { country: "Crawfordsville", emoji: "🇺🇸", index: 353, type: "city" },
  { country: "Camp Verde", emoji: "🇺🇸", index: 354, type: "city" },
  { country: "Dawson", emoji: "🇺🇸", index: 355, type: "city" },
  { country: "Madisonville", emoji: "🇺🇸", index: 356, type: "city" },
  { country: "Carrboro", emoji: "🇺🇸", index: 357, type: "city" },
  { country: "Mount Carmel", emoji: "🇺🇸", index: 358, type: "city" },
  { country: "Williamstown", emoji: "🇺🇸", index: 359, type: "city" },
  { country: "Marshall", emoji: "🇺🇸", index: 360, type: "city" },
  { country: "Elmwood Park", emoji: "🇺🇸", index: 361, type: "city" },
  { country: "Cherry Hills Village", emoji: "🇺🇸", index: 362, type: "city" },
  { country: "Cliffside Park", emoji: "🇺🇸", index: 363, type: "city" },
  { country: "Watsonville", emoji: "🇺🇸", index: 364, type: "city" },
  { country: "Matawan", emoji: "🇺🇸", index: 365, type: "city" },
  { country: "Lindale", emoji: "🇺🇸", index: 366, type: "city" },
  { country: "Albany", emoji: "🇺🇸", index: 367, type: "city" },
  { country: "Paso Robles", emoji: "🇺🇸", index: 368, type: "city" },
  { country: "Fort Thomas", emoji: "🇺🇸", index: 369, type: "city" },
  { country: "Dayton", emoji: "🇺🇸", index: 370, type: "city" },
  { country: "Washington DC", emoji: "🇺🇸", index: 371, type: "city" },
  { country: "Florida", emoji: "🇺🇸", index: 372, type: "country" },
  { country: "Texas", emoji: "🇺🇸", index: 373, type: "country" },
  { country: "Pennsylvania", emoji: "🇺🇸", index: 374, type: "country" },
  { country: "Hawaii", emoji: "🇺🇸", index: 375, type: "country" },
  { country: "Washington", emoji: "🇺🇸", index: 376, type: "country" },
  { country: "North Carolina", emoji: "🇺🇸", index: 377, type: "country" },
  { country: "Michigan", emoji: "🇺🇸", index: 378, type: "country" },
  { country: "Arizona", emoji: "🇺🇸", index: 379, type: "country" },
  { country: "Spokane", emoji: "🇺🇸", index: 380, type: "city" },
  { country: "San Bernardino", emoji: "🇺🇸", index: 381, type: "city" },
  { country: "Tacoma", emoji: "🇺🇸", index: 382, type: "city" },
  { country: "Des Moines", emoji: "🇺🇸", index: 383, type: "city" },
  { country: "Santa Clarita", emoji: "🇺🇸", index: 384, type: "city" },
  { country: "Uruguay", emoji: "🇺🇾", index: 385, type: "country" },
  { country: "Uzbekistan", emoji: "🇺🇿", index: 386, type: "country" },
  { country: "Vanuatu", emoji: "🇻🇺", index: 387, type: "country" },
  { country: "Vatican", emoji: "🇻🇦", index: 388, type: "country" },
  { country: "Venezuela", emoji: "🇻🇪", index: 389, type: "country" },
  { country: "Vietnam", emoji: "🇻🇳", index: 390, type: "country" },
  { country: "Wallis and Futuna", emoji: "🇼🇫", index: 391, type: "country" },
  { country: "Western Sahara", emoji: "🇪🇭", index: 392, type: "country" },
  { country: "Zambia", emoji: "🇿🇲", index: 393, type: "country" },
  { country: "Zimbabwe", emoji: "🇿🇼", index: 394, type: "country" },
  { country: "Alameda", emoji: "🇺🇸", index: 395, type: "city" },
  { country: "American Canyon", emoji: "🇺🇸", index: 396, type: "city" },
  { country: "Antioch", emoji: "🇺🇸", index: 397, type: "city" },
  { country: "Atherton", emoji: "🇺🇸", index: 398, type: "city" },
  { country: "Benicia", emoji: "🇺🇸", index: 399, type: "city" },
  { country: "Brisbane", emoji: "🇺🇸", index: 400, type: "city" },
  { country: "Burlingame", emoji: "🇺🇸", index: 401, type: "city" },
  { country: "Campbell", emoji: "🇺🇸", index: 402, type: "city" },
  { country: "Clayton", emoji: "🇺🇸", index: 403, type: "city" },
  { country: "Colma", emoji: "🇺🇸", index: 404, type: "city" },
  { country: "Corte Madera", emoji: "🇺🇸", index: 405, type: "city" },
  { country: "Daly City", emoji: "🇺🇸", index: 406, type: "city" },
  { country: "Danville", emoji: "🇺🇸", index: 407, type: "city" },
  { country: "East Palo Alto", emoji: "🇺🇸", index: 408, type: "city" },
  { country: "Fairfax", emoji: "🇺🇸", index: 409, type: "city" },
  { country: "Half Moon Bay", emoji: "🇺🇸", index: 410, type: "city" },
  { country: "Healdsburg", emoji: "🇺🇸", index: 411, type: "city" },
  { country: "Larkspur", emoji: "🇺🇸", index: 412, type: "city" },
  { country: "Los Altos", emoji: "🇺🇸", index: 413, type: "city" },
  { country: "Los Altos Hills", emoji: "🇺🇸", index: 414, type: "city" },
  { country: "Los Gatos", emoji: "🇺🇸", index: 415, type: "city" },
  { country: "Martinez", emoji: "🇺🇸", index: 416, type: "city" },
  { country: "Menlo Park", emoji: "🇺🇸", index: 417, type: "city" },
  { country: "Mill Valley", emoji: "🇺🇸", index: 418, type: "city" },
  { country: "Millbrae", emoji: "🇺🇸", index: 419, type: "city" },
  { country: "Milpitas", emoji: "🇺🇸", index: 420, type: "city" },
  { country: "Moraga", emoji: "🇺🇸", index: 421, type: "city" },
  { country: "Morgan Hill", emoji: "🇺🇸", index: 422, type: "city" },
  { country: "Mountain View", emoji: "🇺🇸", index: 423, type: "city" },
  { country: "Oakley", emoji: "🇺🇸", index: 424, type: "city" },
  { country: "Orinda", emoji: "🇺🇸", index: 425, type: "city" },
  { country: "Pacifica", emoji: "🇺🇸", index: 426, type: "city" },
  { country: "Palo Alto", emoji: "🇺🇸", index: 427, type: "city" },
  { country: "Petaluma", emoji: "🇺🇸", index: 428, type: "city" },
  { country: "Pleasanton", emoji: "🇺🇸", index: 429, type: "city" },
  { country: "Pleasant Hill", emoji: "🇺🇸", index: 430, type: "city" },
  { country: "Port Costa", emoji: "🇺🇸", index: 431, type: "city" },
  { country: "Rohnert Park", emoji: "🇺🇸", index: 432, type: "city" },
  { country: "Helena", emoji: "🇺🇸", index: 433, type: "city" },
  { country: "San Anselmo", emoji: "🇺🇸", index: 434, type: "city" },
  { country: "San Bruno", emoji: "🇺🇸", index: 435, type: "city" },
  { country: "San Carlos", emoji: "🇺🇸", index: 436, type: "city" },
  { country: "San Leandro", emoji: "🇺🇸", index: 437, type: "city" },
  { country: "San Mateo", emoji: "🇺🇸", index: 438, type: "city" },
  { country: "San Pablo", emoji: "🇺🇸", index: 439, type: "city" },
  { country: "San Ramon", emoji: "🇺🇸", index: 440, type: "city" },
  { country: "Santa Rosa", emoji: "🇺🇸", index: 441, type: "city" },
  { country: "Saratoga", emoji: "🇺🇸", index: 442, type: "city" },
  { country: "Sausalito", emoji: "🇺🇸", index: 443, type: "city" },
  { country: "Sebastopol", emoji: "🇺🇸", index: 444, type: "city" },
  { country: "Sonoma", emoji: "🇺🇸", index: 445, type: "city" },
  {
    country: "San Francisco Bay Area",
    emoji: "🇺🇸",
    index: 446,
    type: "region",
  },
  { country: "Vallejo", emoji: "🇺🇸", index: 447, type: "city" },
  { country: "Walnut Creek", emoji: "🇺🇸", index: 448, type: "city" },
  { country: "Kabul", emoji: "🇦🇫", index: 449, type: "city" },
  { country: "Algiers", emoji: "🇩🇿", index: 450, type: "city" },
  { country: "Luanda", emoji: "🇦🇴", index: 451, type: "city" },
  { country: "Buenos Aires", emoji: "🇦🇷", index: 452, type: "city" },
  { country: "Cordoba", emoji: "🇦🇷", index: 453, type: "city" },
  { country: "Rosario", emoji: "🇦🇷", index: 454, type: "city" },
  { country: "Mendoza", emoji: "🇦🇷", index: 455, type: "city" },
  { country: "Brisbane", emoji: "🇦🇺", index: 456, type: "city" },
  { country: "Adelaide", emoji: "🇦🇺", index: 457, type: "city" },
  { country: "Vienna", emoji: "🇦🇹", index: 458, type: "city" },
  { country: "Baku", emoji: "🇦🇿", index: 459, type: "city" },
  { country: "Dhaka", emoji: "🇧🇩", index: 460, type: "city" },
  { country: "Chittagong", emoji: "🇧🇩", index: 461, type: "city" },
  { country: "Abomey-Calavi", emoji: "🇧🇯", index: 462, type: "city" },
  { country: "La Paz", emoji: "🇧🇴", index: 463, type: "city" },
  { country: "Santa Cruz", emoji: "🇧🇴", index: 464, type: "city" },
  { country: "Cochabamba", emoji: "🇧🇴", index: 465, type: "city" },
  { country: "Sao Paulo", emoji: "🇧🇷", index: 466, type: "city" },
  { country: "Rio de Janeiro", emoji: "🇧🇷", index: 467, type: "city" },
  { country: "Brasilia", emoji: "🇧🇷", index: 468, type: "city" },
  { country: "Porto Alegre", emoji: "🇧🇷", index: 469, type: "city" },
  { country: "Fortaleza", emoji: "🇧🇷", index: 470, type: "city" },
  { country: "Salvador", emoji: "🇧🇷", index: 471, type: "city" },
  { country: "Curitiba", emoji: "🇧🇷", index: 472, type: "city" },
  { country: "Campinas", emoji: "🇧🇷", index: 473, type: "city" },
  { country: "Goiania", emoji: "🇧🇷", index: 474, type: "city" },
  { country: "Manaus", emoji: "🇧🇷", index: 475, type: "city" },
  { country: "Grande Vitoria", emoji: "🇧🇷", index: 476, type: "region" },
  { country: "Baixada Santista", emoji: "🇧🇷", index: 477, type: "region" },
  { country: "Natal", emoji: "🇧🇷", index: 478, type: "city" },
  { country: "Grande Sao Luis", emoji: "🇧🇷", index: 479, type: "region" },
  { country: "Joao Pessoa", emoji: "🇧🇷", index: 480, type: "city" },
  { country: "Maceio", emoji: "🇧🇷", index: 481, type: "city" },
  { country: "Florianopolis", emoji: "🇧🇷", index: 482, type: "city" },
  { country: "Sofia", emoji: "🇧🇬", index: 483, type: "city" },
  { country: "Ouagadougou", emoji: "🇧🇫", index: 484, type: "city" },
  { country: "Bujumbura", emoji: "🇧🇮", index: 485, type: "city" },
  { country: "Yaounde", emoji: "🇨🇲", index: 486, type: "city" },
  { country: "Douala", emoji: "🇨🇲", index: 487, type: "city" },
  { country: "Montreal", emoji: "🇨🇦", index: 488, type: "city" },
  { country: "Vancouver", emoji: "🇨🇦", index: 489, type: "city" },
  { country: "Calgary", emoji: "🇨🇦", index: 490, type: "city" },
  { country: "Ottawa", emoji: "🇨🇦", index: 491, type: "city" },
  { country: "N-Djamena", emoji: "🇹🇩", index: 492, type: "city" },
  { country: "Santiago", emoji: "🇨🇱", index: 493, type: "city" },
  { country: "Shanghai", emoji: "🇨🇳", index: 494, type: "city" },
  { country: "Tianjin", emoji: "🇨🇳", index: 495, type: "city" },
  { country: "Guangzhou", emoji: "🇨🇳", index: 496, type: "city" },
  { country: "Nanjing", emoji: "🇨🇳", index: 497, type: "city" },
  { country: "Wuhan", emoji: "🇨🇳", index: 498, type: "city" },
  { country: "Xi-an Shaanxi", emoji: "🇨🇳", index: 499, type: "city" },
  { country: "Hangzhou", emoji: "🇨🇳", index: 500, type: "city" },
  { country: "Shenyang", emoji: "🇨🇳", index: 501, type: "city" },
  { country: "Dongguan", emoji: "🇨🇳", index: 502, type: "city" },
  { country: "Foshan", emoji: "🇨🇳", index: 503, type: "city" },
  { country: "Haerbin", emoji: "🇨🇳", index: 504, type: "city" },
  { country: "Dalian", emoji: "🇨🇳", index: 505, type: "city" },
  { country: "Qingdao", emoji: "🇨🇳", index: 506, type: "city" },
  { country: "Ji-nan Shandong", emoji: "🇨🇳", index: 507, type: "city" },
  { country: "Changsha", emoji: "🇨🇳", index: 508, type: "city" },
  { country: "Changchun", emoji: "🇨🇳", index: 509, type: "city" },
  { country: "Shantou", emoji: "🇨🇳", index: 510, type: "city" },
  { country: "Shijiazhuang", emoji: "🇨🇳", index: 511, type: "city" },
  { country: "Nanning", emoji: "🇨🇳", index: 512, type: "city" },
  { country: "Taiyuan Shanxi", emoji: "🇨🇳", index: 513, type: "city" },
  { country: "Changzhou", emoji: "🇨🇳", index: 514, type: "city" },
  { country: "Xiamen", emoji: "🇨🇳", index: 515, type: "city" },
  { country: "Fuzhou Fujian", emoji: "🇨🇳", index: 516, type: "city" },
  { country: "Nanchang", emoji: "🇨🇳", index: 517, type: "city" },
  { country: "Tangshan Hebei", emoji: "🇨🇳", index: 518, type: "city" },
  { country: "Guiyang", emoji: "🇨🇳", index: 519, type: "city" },
  { country: "Lanzhou", emoji: "🇨🇳", index: 520, type: "city" },
  { country: "Zhongshan", emoji: "🇨🇳", index: 521, type: "city" },
  { country: "Handan", emoji: "🇨🇳", index: 522, type: "city" },
  { country: "Huaian", emoji: "🇨🇳", index: 523, type: "city" },
  { country: "Weifang", emoji: "🇨🇳", index: 524, type: "city" },
  { country: "Shaoxing", emoji: "🇨🇳", index: 525, type: "city" },
  { country: "Yantai", emoji: "🇨🇳", index: 526, type: "city" },
  { country: "Luoyang", emoji: "🇨🇳", index: 527, type: "city" },
  { country: "Nantong", emoji: "🇨🇳", index: 528, type: "city" },
  { country: "Baotou", emoji: "🇨🇳", index: 529, type: "city" },
  { country: "Putian", emoji: "🇨🇳", index: 530, type: "city" },
  { country: "Yangzhou", emoji: "🇨🇳", index: 531, type: "city" },
  { country: "Baoding", emoji: "🇨🇳", index: 532, type: "city" },
  { country: "Taizhou Zhejiang", emoji: "🇨🇳", index: 533, type: "city" },
  { country: "Wuhu Anhui", emoji: "🇨🇳", index: 534, type: "city" },
  { country: "Linyi Shandong", emoji: "🇨🇳", index: 535, type: "city" },
  { country: "Haikou", emoji: "🇨🇳", index: 536, type: "city" },
  { country: "Daqing", emoji: "🇨🇳", index: 537, type: "city" },
  { country: "Yancheng Jiangsu", emoji: "🇨🇳", index: 538, type: "city" },
  { country: "Lianyungang", emoji: "🇨🇳", index: 539, type: "city" },
  { country: "Zhuhai", emoji: "🇨🇳", index: 540, type: "city" },
  { country: "Datong", emoji: "🇨🇳", index: 541, type: "city" },
  { country: "Quanzhou", emoji: "🇨🇳", index: 542, type: "city" },
  { country: "Jiangmen", emoji: "🇨🇳", index: 543, type: "city" },
  { country: "Xiangyang", emoji: "🇨🇳", index: 544, type: "city" },
  { country: "Yinchuan", emoji: "🇨🇳", index: 545, type: "city" },
  { country: "Anshan", emoji: "🇨🇳", index: 546, type: "city" },
  { country: "Yichang", emoji: "🇨🇳", index: 547, type: "city" },
  { country: "Qinhuangdao", emoji: "🇨🇳", index: 548, type: "city" },
  { country: "Hengyang", emoji: "🇨🇳", index: 549, type: "city" },
  { country: "Qiqihaer", emoji: "🇨🇳", index: 550, type: "city" },
  { country: "Suqian", emoji: "🇨🇳", index: 551, type: "city" },
  { country: "Anyang", emoji: "🇨🇳", index: 552, type: "city" },
  { country: "Jining Shandong", emoji: "🇨🇳", index: 553, type: "city" },
  { country: "Zhangjiakou", emoji: "🇨🇳", index: 554, type: "city" },
  { country: "Huainan", emoji: "🇨🇳", index: 555, type: "city" },
  { country: "Chaozhou", emoji: "🇨🇳", index: 556, type: "city" },
  { country: "Taizhou Jiangsu", emoji: "🇨🇳", index: 557, type: "city" },
  { country: "Ganzhou", emoji: "🇨🇳", index: 558, type: "city" },
  { country: "Taian Shandong", emoji: "🇨🇳", index: 559, type: "city" },
  { country: "Weihai", emoji: "🇨🇳", index: 560, type: "city" },
  { country: "Jiaxing", emoji: "🇨🇳", index: 561, type: "city" },
  { country: "Kaifeng", emoji: "🇨🇳", index: 562, type: "city" },
  { country: "Rizhao", emoji: "🇨🇳", index: 563, type: "city" },
  { country: "Zhanjiang", emoji: "🇨🇳", index: 564, type: "city" },
  { country: "Nanchong", emoji: "🇨🇳", index: 565, type: "city" },
  { country: "Mianyang Sichuan", emoji: "🇨🇳", index: 566, type: "city" },
  { country: "Liuan", emoji: "🇨🇳", index: 567, type: "city" },
  { country: "Shiyan", emoji: "🇨🇳", index: 568, type: "city" },
  { country: "Liuyang", emoji: "🇨🇳", index: 569, type: "city" },
  { country: "Fushun Liaoning", emoji: "🇨🇳", index: 570, type: "city" },
  { country: "Maoming", emoji: "🇨🇳", index: 571, type: "city" },
  { country: "Ruian", emoji: "🇨🇳", index: 572, type: "city" },
  { country: "Jieyang", emoji: "🇨🇳", index: 573, type: "city" },
  { country: "Baoji", emoji: "🇨🇳", index: 574, type: "city" },
  { country: "Pingdingshan Henan", emoji: "🇨🇳", index: 575, type: "city" },
  { country: "Zhenjiang Jiangsu", emoji: "🇨🇳", index: 576, type: "city" },
  { country: "Jinhua", emoji: "🇨🇳", index: 577, type: "city" },
  { country: "Huaibei", emoji: "🇨🇳", index: 578, type: "city" },
  { country: "Nanyang Henan", emoji: "🇨🇳", index: 579, type: "city" },
  { country: "Xiangtan Hunan", emoji: "🇨🇳", index: 580, type: "city" },
  { country: "Liupanshui", emoji: "🇨🇳", index: 581, type: "city" },
  { country: "Xinxiang", emoji: "🇨🇳", index: 582, type: "city" },
  { country: "Bogota", emoji: "🇨🇴", index: 583, type: "city" },
  { country: "Cali", emoji: "🇨🇴", index: 584, type: "city" },
  { country: "Barranquilla", emoji: "🇨🇴", index: 585, type: "city" },
  { country: "Bucaramanga", emoji: "🇨🇴", index: 586, type: "city" },
  { country: "San Jose", emoji: "🇨🇷", index: 587, type: "city" },
  { country: "Havana", emoji: "🇨🇺", index: 588, type: "city" },
  { country: "Prague", emoji: "🇨🇿", index: 589, type: "city" },
  { country: "Copenhagen", emoji: "🇩🇰", index: 590, type: "city" },
  { country: "Santo Domingo", emoji: "🇩🇴", index: 591, type: "city" },
  { country: "Kinshasa", emoji: "🇨🇩", index: 592, type: "city" },
  { country: "Mbuji-Mayi", emoji: "🇨🇩", index: 593, type: "city" },
  { country: "Lubumbashi", emoji: "🇨🇩", index: 594, type: "city" },
  { country: "Kananga", emoji: "🇨🇩", index: 595, type: "city" },
  { country: "Kisangani", emoji: "🇨🇩", index: 596, type: "city" },
  { country: "Bukavu", emoji: "🇨🇩", index: 597, type: "city" },
  { country: "Guayaquil", emoji: "🇪🇨", index: 598, type: "city" },
  { country: "Cairo", emoji: "🇪🇬", index: 599, type: "city" },
  { country: "Alexandria", emoji: "🇪🇬", index: 600, type: "city" },
  { country: "Addis Ababa", emoji: "🇪🇹", index: 601, type: "city" },
  { country: "Paris", emoji: "🇫🇷", index: 602, type: "city" },
  { country: "Marseille", emoji: "🇫🇷", index: 603, type: "city" },
  { country: "Hamburg", emoji: "de", index: 604, type: "city" },
  { country: "Kumasi", emoji: "gh", index: 605, type: "city" },
  { country: "Accra", emoji: "gh", index: 606, type: "city" },
  { country: "Athens", emoji: "gr", index: 607, type: "city" },
  { country: "Guatemala City", emoji: "gt", index: 608, type: "city" },
  { country: "Conakry", emoji: "gn", index: 609, type: "city" },
  { country: "Port-au-Prince", emoji: "ht", index: 610, type: "city" },
  { country: "Tegucigalpa", emoji: "hn", index: 611, type: "city" },
  { country: "Budapest", emoji: "hu", index: 612, type: "city" },
  { country: "Mumbai", emoji: "in", index: 613, type: "city" },
  { country: "Kolkata", emoji: "in", index: 614, type: "city" },
  { country: "Bangalore", emoji: "in", index: 615, type: "city" },
  { country: "Chennai", emoji: "in", index: 616, type: "city" },
  { country: "Hyderabad", emoji: "in", index: 617, type: "city" },
  { country: "Ahmedabad", emoji: "in", index: 618, type: "city" },
  { country: "Surat", emoji: "in", index: 619, type: "city" },
  { country: "Jaipur", emoji: "in", index: 620, type: "city" },
  { country: "Malappuram", emoji: "in", index: 621, type: "city" },
  { country: "Kanpur", emoji: "in", index: 622, type: "city" },
  { country: "Nagpur", emoji: "in", index: 623, type: "city" },
  { country: "Coimbatore", emoji: "in", index: 624, type: "city" },
  { country: "Thiruvananthapuram", emoji: "in", index: 625, type: "city" },
  { country: "Patna", emoji: "in", index: 626, type: "city" },
  { country: "Bhopal", emoji: "in", index: 627, type: "city" },
  { country: "Agra", emoji: "in", index: 628, type: "city" },
  { country: "Kannur", emoji: "in", index: 629, type: "city" },
  { country: "Visakhapatnam", emoji: "in", index: 630, type: "city" },
  { country: "Vadodara", emoji: "in", index: 631, type: "city" },
  { country: "Nashik", emoji: "in", index: 632, type: "city" },
  { country: "Vijayawada", emoji: "in", index: 633, type: "city" },
  { country: "Kollam", emoji: "in", index: 634, type: "city" },
  { country: "Rajkot", emoji: "in", index: 635, type: "city" },
  { country: "Ludhiana", emoji: "in", index: 636, type: "city" },
  { country: "Madurai", emoji: "in", index: 637, type: "city" },
  { country: "Raipur", emoji: "in", index: 638, type: "city" },
  { country: "Varanasi", emoji: "in", index: 639, type: "city" },
  { country: "Jamshedpur", emoji: "in", index: 640, type: "city" },
  { country: "Srinagar", emoji: "in", index: 641, type: "city" },
  { country: "Aurangabad", emoji: "in", index: 642, type: "city" },
  { country: "Ranchi", emoji: "in", index: 643, type: "city" },
  { country: "Jabalpur", emoji: "in", index: 644, type: "city" },
  { country: "Asansol", emoji: "in", index: 645, type: "city" },
  { country: "Kota", emoji: "in", index: 646, type: "city" },
  { country: "Gwalior", emoji: "in", index: 647, type: "city" },
  { country: "Allahabad", emoji: "in", index: 648, type: "city" },
  { country: "Amritsar", emoji: "in", index: 649, type: "city" },
  { country: "Dhanbad", emoji: "in", index: 650, type: "city" },
  { country: "Bareilly", emoji: "in", index: 651, type: "city" },
  { country: "Aligarh", emoji: "in", index: 652, type: "city" },
  { country: "Moradabad", emoji: "in", index: 653, type: "city" },
  { country: "Durg-Bhilainagar", emoji: "in", index: 654, type: "city" },
  { country: "Bhubaneswar", emoji: "in", index: 655, type: "city" },
  { country: "Tiruchirappalli", emoji: "in", index: 656, type: "city" },
  { country: "Chandigarh", emoji: "in", index: 657, type: "city" },
  { country: "Hubli-Dharwad", emoji: "in", index: 658, type: "city" },
  { country: "Guwahati", emoji: "in", index: 659, type: "city" },
  { country: "Salem", emoji: "in", index: 660, type: "city" },
  { country: "Saharanpur", emoji: "in", index: 661, type: "city" },
  { country: "Jakarta", emoji: "id", index: 662, type: "city" },
  { country: "Bekasi", emoji: "id", index: 663, type: "city" },
  { country: "Surabaya", emoji: "id", index: 664, type: "city" },
  { country: "Bandung", emoji: "id", index: 665, type: "city" },
  { country: "Tangerang", emoji: "id", index: 666, type: "city" },
  { country: "Medan", emoji: "id", index: 667, type: "city" },
  { country: "Semarang", emoji: "id", index: 668, type: "city" },
  { country: "Palembang", emoji: "id", index: 669, type: "city" },
  { country: "Batam", emoji: "id", index: 670, type: "city" },
  { country: "Makassar", emoji: "id", index: 671, type: "city" },
  { country: "Pekan Baru", emoji: "id", index: 672, type: "city" },
  { country: "Tasikmalaya", emoji: "id", index: 673, type: "city" },
  { country: "Bandar Lampung", emoji: "id", index: 674, type: "city" },
  { country: "Tehran", emoji: "ir", index: 675, type: "city" },
  { country: "Mashhad", emoji: "ir", index: 676, type: "city" },
  { country: "Esfahan", emoji: "ir", index: 677, type: "city" },
  { country: "Shiraz", emoji: "ir", index: 678, type: "city" },
  { country: "Tabriz", emoji: "ir", index: 679, type: "city" },
  { country: "Karaj", emoji: "ir", index: 680, type: "city" },
  { country: "Ahvaz", emoji: "ir", index: 681, type: "city" },
  { country: "Baghdad", emoji: "iq", index: 682, type: "city" },
  { country: "Basra", emoji: "iq", index: 683, type: "city" },
  { country: "Tel Aviv", emoji: "il", index: 684, type: "city" },
  { country: "Haifa", emoji: "il", index: 685, type: "city" },
  { country: "Milan", emoji: "it", index: 686, type: "city" },
  { country: "Naples", emoji: "it", index: 687, type: "city" },
  { country: "Abidjan", emoji: "ci", index: 688, type: "city" },
  { country: "Osaka", emoji: "jp", index: 689, type: "city" },
  { country: "Nagoya", emoji: "jp", index: 690, type: "city" },
  { country: "Fukuoka", emoji: "jp", index: 691, type: "city" },
  { country: "Shizuoka", emoji: "jp", index: 692, type: "city" },
  { country: "Sapporo", emoji: "jp", index: 693, type: "city" },
  { country: "Sendai", emoji: "jp", index: 694, type: "city" },
  { country: "Hiroshima", emoji: "jp", index: 695, type: "city" },
  { country: "Amman", emoji: "jo", index: 696, type: "city" },
  { country: "Almaty", emoji: "kz", index: 697, type: "city" },
  { country: "Astana", emoji: "kz", index: 698, type: "city" },
  { country: "Nairobi", emoji: "ke", index: 699, type: "city" },
  { country: "Mombasa", emoji: "ke", index: 700, type: "city" },
  { country: "Kuwait City", emoji: "kw", index: 701, type: "city" },
  { country: "Monrovia", emoji: "lr", index: 702, type: "city" },
  { country: "Antananarivo", emoji: "mg", index: 703, type: "city" },
  { country: "Kuala Lumpur", emoji: "my", index: 704, type: "city" },
  { country: "Bamako", emoji: "ml", index: 705, type: "city" },
  { country: "Nouakchott", emoji: "mr", index: 706, type: "city" },
  { country: "Guadalajara", emoji: "mx", index: 707, type: "city" },
  { country: "Puebla", emoji: "mx", index: 708, type: "city" },
  { country: "Toluca de Lerdo", emoji: "mx", index: 709, type: "city" },
  { country: "Tijuana", emoji: "mx", index: 710, type: "city" },
  { country: "Leon de los Aldamas", emoji: "mx", index: 711, type: "city" },
  { country: "La Laguna", emoji: "mx", index: 712, type: "city" },
  { country: "Ciudad Juarez", emoji: "mx", index: 713, type: "city" },
  { country: "Queretaro", emoji: "mx", index: 714, type: "city" },
  { country: "San Luis Potosi", emoji: "mx", index: 715, type: "city" },
  { country: "Merida", emoji: "mx", index: 716, type: "city" },
  { country: "Mexicali", emoji: "mx", index: 717, type: "city" },
  { country: "Aguascalientes", emoji: "mx", index: 718, type: "city" },
  { country: "Ulaanbaatar", emoji: "mn", index: 719, type: "city" },
  { country: "Casablanca", emoji: "ma", index: 720, type: "city" },
  { country: "Rabat", emoji: "ma", index: 721, type: "city" },
  { country: "Tanger", emoji: "ma", index: 722, type: "city" },
  { country: "Matola", emoji: "mz", index: 723, type: "city" },
  { country: "Maputo", emoji: "mz", index: 724, type: "city" },
  { country: "Yangon", emoji: "mm", index: 725, type: "city" },
  { country: "Mandalay", emoji: "mm", index: 726, type: "city" },
  { country: "Kathmandu", emoji: "np", index: 727, type: "city" },
  { country: "Amsterdam", emoji: "nl", index: 728, type: "city" },
  { country: "Auckland", emoji: "nz", index: 729, type: "city" },
  { country: "Niamey", emoji: "ne", index: 730, type: "city" },
  { country: "Lagos", emoji: "ng", index: 731, type: "city" },
  { country: "Kano", emoji: "ng", index: 732, type: "city" },
  { country: "Ibadan", emoji: "ng", index: 733, type: "city" },
  { country: "Abuja", emoji: "ng", index: 734, type: "city" },
  { country: "Port Harcourt", emoji: "ng", index: 735, type: "city" },
  { country: "Onitsha", emoji: "ng", index: 736, type: "city" },
  { country: "Kaduna", emoji: "ng", index: 737, type: "city" },
  { country: "Aba", emoji: "ng", index: 738, type: "city" },
  { country: "Pyongyang", emoji: "kp", index: 739, type: "city" },
  { country: "Muscat", emoji: "om", index: 740, type: "city" },
  { country: "Karachi", emoji: "pk", index: 741, type: "city" },
  { country: "Lahore", emoji: "pk", index: 742, type: "city" },
  { country: "Faisalabad", emoji: "pk", index: 743, type: "city" },
  { country: "Gujranwala", emoji: "pk", index: 744, type: "city" },
  { country: "Peshawar", emoji: "pk", index: 745, type: "city" },
  { country: "Rawalpindi", emoji: "pk", index: 746, type: "city" },
  { country: "Multan", emoji: "pk", index: 747, type: "city" },
  { country: "Hyderabad", emoji: "pk", index: 748, type: "city" },
  { country: "Islamabad", emoji: "pk", index: 749, type: "city" },
  { country: "Quetta", emoji: "pk", index: 750, type: "city" },
  { country: "Panama City", emoji: "pa", index: 751, type: "city" },
  { country: "Asuncion", emoji: "py", index: 752, type: "city" },
  { country: "Lima", emoji: "pe", index: 753, type: "city" },
  { country: "Manila", emoji: "ph", index: 754, type: "city" },
  { country: "Davao City", emoji: "ph", index: 755, type: "city" },
  { country: "Warsaw", emoji: "pl", index: 756, type: "city" },
  { country: "San Juan", emoji: "pr", index: 757, type: "city" },
  { country: "Doha", emoji: "qa", index: 758, type: "city" },
  { country: "Brazzaville", emoji: "cg", index: 759, type: "city" },
  { country: "Bucharest", emoji: "ro", index: 760, type: "city" },
  { country: "Saint Petersburg", emoji: "ru", index: 761, type: "city" },
  { country: "Yekaterinburg", emoji: "ru", index: 762, type: "city" },
  { country: "Kazan", emoji: "ru", index: 763, type: "city" },
  { country: "Chelyabinsk", emoji: "ru", index: 764, type: "city" },
  { country: "Krasnoyarsk", emoji: "ru", index: 765, type: "city" },
  { country: "Samara", emoji: "ru", index: 766, type: "city" },
  { country: "Ufa", emoji: "ru", index: 767, type: "city" },
  { country: "Kigali", emoji: "rw", index: 768, type: "city" },
  { country: "Riyadh", emoji: "sa", index: 769, type: "city" },
  { country: "Jiddah", emoji: "sa", index: 770, type: "city" },
  { country: "Mecca", emoji: "sa", index: 771, type: "city" },
  { country: "Medina", emoji: "sa", index: 772, type: "city" },
  { country: "Ad-Dammam", emoji: "sa", index: 773, type: "city" },
  { country: "Dakar", emoji: "sn", index: 774, type: "city" },
  { country: "Belgrade", emoji: "rs", index: 775, type: "city" },
  { country: "Mogadishu", emoji: "so", index: 776, type: "city" },
  { country: "Johannesburg", emoji: "za", index: 777, type: "city" },
  { country: "Cape Town", emoji: "za", index: 778, type: "city" },
  { country: "Durban", emoji: "za", index: 779, type: "city" },
  { country: "Pretoria", emoji: "za", index: 780, type: "city" },
  { country: "Port Elizabeth", emoji: "za", index: 781, type: "city" },
  { country: "Busan", emoji: "kr", index: 782, type: "city" },
  { country: "Daegu", emoji: "kr", index: 783, type: "city" },
  { country: "Daejon", emoji: "kr", index: 784, type: "city" },
  { country: "Gwangju", emoji: "kr", index: 785, type: "city" },
  { country: "Madrid", emoji: "es", index: 786, type: "city" },
  { country: "Barcelona", emoji: "es", index: 787, type: "city" },
  { country: "Khartoum", emoji: "sd", index: 788, type: "city" },
  { country: "Damascus", emoji: "sy", index: 789, type: "city" },
  { country: "Aleppo", emoji: "sy", index: 790, type: "city" },
  { country: "Taipei", emoji: "tw", index: 791, type: "city" },
  { country: "Taoyuan", emoji: "tw", index: 792, type: "city" },
  { country: "Gaoxiong", emoji: "tw", index: 793, type: "city" },
  { country: "Taizhong", emoji: "tw", index: 794, type: "city" },
  { country: "Dar es Salaam", emoji: "tz", index: 795, type: "city" },
  { country: "Mwanza", emoji: "tz", index: 796, type: "city" },
  { country: "Bangkok", emoji: "th", index: 797, type: "city" },
  { country: "Samut Prakan", emoji: "th", index: 798, type: "city" },
  { country: "Chiang Mai", emoji: "th", index: 799, type: "city" },
  { country: "Istanbul", emoji: "tr", index: 800, type: "city" },
  { country: "Ankara", emoji: "🇹🇷", index: 801, type: "city" },
  { country: "Bursa", emoji: "🇹🇷", index: 802, type: "city" },
  { country: "Adana", emoji: "🇹🇷", index: 803, type: "city" },
  { country: "Gaziantep", emoji: "🇹🇷", index: 804, type: "city" },
  { country: "Konya", emoji: "🇹🇷", index: 805, type: "city" },
  { country: "Antalya", emoji: "🇹🇷", index: 806, type: "city" },
  { country: "Kampala", emoji: "🇺🇬", index: 807, type: "city" },
  { country: "Kharkiv", emoji: "🇺🇦", index: 808, type: "city" },
  { country: "Dubai", emoji: "🇦🇪", index: 809, type: "city" },
  { country: "Sharjah", emoji: "🇦🇪", index: 810, type: "city" },
  { country: "Abu Dhabi", emoji: "🇦🇪", index: 811, type: "city" },
  { country: "Manchester", emoji: "🇬🇧", index: 812, type: "city" },
  { country: "Birmingham", emoji: "🇬🇧", index: 813, type: "city" },
  { country: "Glasgow", emoji: "🇬🇧", index: 814, type: "city" },
  { country: "Tashkent", emoji: "🇺🇿", index: 815, type: "city" },

  { country: "Caracas", emoji: "🇻🇪", index: 816, type: "city" },
  { country: "Maracaibo", emoji: "🇻🇪", index: 817, type: "city" },
  { country: "Valencia", emoji: "🇻🇪", index: 818, type: "city" },
  { country: "Barquisimeto", emoji: "🇻🇪", index: 819, type: "city" },
  { country: "Maracay", emoji: "🇻🇪", index: 820, type: "city" },
  { country: "Hanoi", emoji: "🇻🇳", index: 821, type: "city" },
  { country: "Can Tho", emoji: "🇻🇳", index: 822, type: "city" },
  { country: "Hai Phong", emoji: "🇻🇳", index: 823, type: "city" },
  { country: "Da Nang", emoji: "🇻🇳", index: 824, type: "city" },
  { country: "Sanaa", emoji: "🇾🇪", index: 825, type: "city" },
  { country: "Lusaka", emoji: "🇿🇲", index: 826, type: "city" },
  { country: "Harare", emoji: "🇿🇼", index: 827, type: "city" },
  { country: "Belgium", emoji: "🇧🇪", index: 828, type: "country" },
  { country: "Belize", emoji: "🇧🇿", index: 829, type: "country" },
  { country: "Benin", emoji: "🇧🇯", index: 830, type: "country" },
  { country: "Brunei", emoji: "🇧🇳", index: 831, type: "country" },
  { country: "Burundi", emoji: "🇧🇮", index: 832, type: "country" },
  { country: "Czech Republic", emoji: "🇨🇿", index: 833, type: "country" },
  { country: "Djibouti", emoji: "🇩🇯", index: 834, type: "country" },
  { country: "Luxembourg", emoji: "🇱🇺", index: 835, type: "country" },
  {
    country: "Republic of the Congo",
    emoji: "🇨🇬",
    index: 836,
    type: "country",
  },
  { country: "Columbus", emoji: "🇺🇸", index: 837, type: "city" },
  { country: "Boston", emoji: "🇺🇸", index: 838, type: "city" },
  { country: "Pittsburgh", emoji: "🇺🇸", index: 839, type: "city" },
  { country: "Greensboro", emoji: "🇺🇸", index: 840, type: "city" },
  { country: "St. Petersburg", emoji: "🇺🇸", index: 841, type: "city" },
  { country: "Lubbock", emoji: "🇺🇸", index: 842, type: "city" },
  { country: "Boise", emoji: "🇺🇸", index: 843, type: "city" },
  { country: "Boise City", emoji: "🇺🇸", index: 844, type: "city" },
  { country: "Brownsville", emoji: "🇺🇸", index: 845, type: "city" },
  { country: "Pembroke Pines", emoji: "🇺🇸", index: 846, type: "city" },
  { country: "Bridgeport", emoji: "🇺🇸", index: 847, type: "city" },
  { country: "Berkeley", emoji: "🇺🇸", index: 848, type: "city" },
  { country: "Billings", emoji: "🇺🇸", index: 849, type: "city" },
  { country: "Murfreesboro", emoji: "🇺🇸", index: 850, type: "city" },
  { country: "Bloomington", emoji: "🇺🇸", index: 851, type: "city" },
  { country: "Bellevue", emoji: "🇺🇸", index: 852, type: "city" },
  { country: "Greensburg", emoji: "🇺🇸", index: 853, type: "city" },
  { country: "Bedford", emoji: "🇺🇸", index: 854, type: "city" },
  { country: "Bridgeton", emoji: "🇺🇸", index: 855, type: "city" },
  { country: "Bucyrus", emoji: "🇺🇸", index: 856, type: "city" },
  { country: "Gibsonville", emoji: "🇺🇸", index: 857, type: "city" },
  { country: "Belmont", emoji: "🇺🇸", index: 858, type: "city" },
  { country: "Belvedere", emoji: "🇺🇸", index: 859, type: "city" },
  { country: "Dublin", emoji: "🇺🇸", index: 860, type: "city" },
  { country: "Hillsborough", emoji: "🇺🇸", index: 861, type: "city" },
  { country: "Pittsburg", emoji: "🇺🇸", index: 862, type: "city" },
  { country: "Tiburon", emoji: "🇺🇸", index: 863, type: "city" },
  { country: "Melbourne", emoji: "🇦🇺", index: 864, type: "city" },
  { country: "Brussels", emoji: "🇧🇪", index: 865, type: "city" },
  { country: "Belo Horizonte", emoji: "🇧🇷", index: 866, type: "city" },
  { country: "Belem", emoji: "🇧🇷", index: 867, type: "city" },
  { country: "Beijing", emoji: "🇨🇳", index: 868, type: "city" },
  { country: "Ningbo", emoji: "🇨🇳", index: 869, type: "city" },
  { country: "Zibo", emoji: "🇨🇳", index: 870, type: "city" },
  { country: "Benxi", emoji: "🇨🇳", index: 871, type: "city" },
  { country: "Binzhou", emoji: "🇨🇳", index: 872, type: "city" },
  { country: "Berlin", emoji: "🇩🇪", index: 873, type: "city" },
  { country: "Bogor", emoji: "🇮🇩", index: 874, type: "city" },
  { country: "Dublin", emoji: "🇮🇪", index: 875, type: "city" },
  { country: "Beirut", emoji: "🇱🇧", index: 876, type: "city" },
  { country: "Benin City", emoji: "🇳🇬", index: 877, type: "city" },
  { country: "Lisbon", emoji: "🇵🇹", index: 878, type: "city" },
  { country: "Novosibirsk", emoji: "🇷🇺", index: 879, type: "city" },
  { country: "Xinbei", emoji: "🇹🇼", index: 880, type: "city" },
  { country: "Chon Buri", emoji: "🇹🇭", index: 881, type: "city" },
  { country: "Chile", emoji: "🇨🇱", index: 882, type: "country" },
  { country: "Comoros", emoji: "🇰🇲", index: 883, type: "country" },
  { country: "Cyprus", emoji: "🇨🇾", index: 884, type: "country" },
  {
    country: "French Southern Territories",
    emoji: "🇹🇫",
    index: 885,
    type: "country",
  },
  { country: "Greece", emoji: "🇬🇷", index: 886, type: "country" },
  { country: "Liechtenstein", emoji: "🇱🇮", index: 887, type: "country" },
  { country: "Mexico", emoji: "🇲🇽", index: 888, type: "country" },
  { country: "Morocco", emoji: "🇲🇦", index: 889, type: "country" },
  { country: "Puerto Rico", emoji: "🇵🇷", index: 890, type: "country" },
  { country: "Seychelles", emoji: "🇸🇨", index: 891, type: "country" },
  { country: "New York City", emoji: "🇺🇸", index: 892, type: "city" },
  { country: "Tucson", emoji: "🇺🇸", index: 893, type: "city" },
  { country: "Corpus Christi", emoji: "🇺🇸", index: 894, type: "city" },
  { country: "Stockton", emoji: "🇺🇸", index: 895, type: "city" },
  { country: "Lincoln", emoji: "🇺🇸", index: 896, type: "city" },
  { country: "Jersey City", emoji: "🇺🇸", index: 897, type: "city" },
  { country: "Rochester", emoji: "🇺🇸", index: 898, type: "city" },
  { country: "Little Rock", emoji: "🇺🇸", index: 899, type: "city" },
  { country: "Port St. Lucie", emoji: "🇺🇸", index: 900, type: "city" },
  { country: "Fort Collins", emoji: "🇺🇸", index: 901, type: "city" },
  { country: "Escondido", emoji: "🇺🇸", index: 902, type: "city" },
  { country: "Rockford", emoji: "🇺🇸", index: 903, type: "city" },
  { country: "Frisco", emoji: "🇺🇸", index: 904, type: "city" },
  { country: "McKinney", emoji: "🇺🇸", index: 905, type: "city" },
  { country: "Independence", emoji: "🇺🇸", index: 906, type: "city" },
  { country: "Round Rock", emoji: "🇺🇸", index: 907, type: "city" },
  { country: "St. Cloud", emoji: "🇺🇸", index: 908, type: "city" },
  { country: "Lompoc", emoji: "🇺🇸", index: 909, type: "city" },
  { country: "Chillicothe", emoji: "🇺🇸", index: 910, type: "city" },
  { country: "Hercules", emoji: "🇺🇸", index: 911, type: "city" },
  { country: "El Cerrito", emoji: "🇺🇸", index: 912, type: "city" },
  { country: "Crestview", emoji: "🇺🇸", index: 913, type: "city" },
  { country: "Cresskill", emoji: "🇺🇸", index: 914, type: "city" },
  { country: "Crestwood", emoji: "🇺🇸", index: 915, type: "city" },
  { country: "Concord", emoji: "🇺🇸", index: 916, type: "city" },
  { country: "Cupertino", emoji: "🇺🇸", index: 917, type: "city" },
  { country: "Foster City", emoji: "🇺🇸", index: 918, type: "city" },
  { country: "Redwood City", emoji: "🇺🇸", index: 919, type: "city" },
  { country: "Richmond", emoji: "🇺🇸", index: 920, type: "city" },
  { country: "Suisun City", emoji: "🇺🇸", index: 921, type: "city" },
  { country: "Union City", emoji: "🇺🇸", index: 922, type: "city" },
  { country: "Recife", emoji: "🇧🇷", index: 923, type: "city" },
  { country: "Chongqing", emoji: "🇨🇳", index: 924, type: "city" },
  { country: "Chengdu", emoji: "🇨🇳", index: 925, type: "city" },
  { country: "Cixi", emoji: "🇨🇳", index: 926, type: "city" },
  { country: "Chifeng", emoji: "🇨🇳", index: 927, type: "city" },
  { country: "Munich", emoji: "🇩🇪", index: 928, type: "city" },
  { country: "Cologne", emoji: "🇩🇪", index: 929, type: "city" },
  { country: "Lucknow", emoji: "🇮🇳", index: 930, type: "city" },

  { country: "Kochi", emoji: "🇮🇳", index: 931, type: "city" },
  { country: "Mexico City", emoji: "🇲🇽", index: 932, type: "city" },
  { country: "Moscow", emoji: "🇷🇺", index: 933, type: "city" },
  { country: "Incheon", emoji: "🇰🇷", index: 934, type: "city" },
  { country: "Stockholm", emoji: "🇸🇪", index: 935, type: "city" },
  { country: "Zurich", emoji: "🇨🇭", index: 936, type: "city" },
  { country: "Ho Chi Minh City", emoji: "🇻🇳", index: 937, type: "city" },
  { country: "Sweden", emoji: "🇸🇪", index: 938, type: "country" },
  { country: "United Kingdom", emoji: "🇬🇧", index: 939, type: "country" },
  { country: "Denver", emoji: "🇺🇸", index: 940, type: "city" },
  { country: "Detroit", emoji: "🇺🇸", index: 941, type: "city" },
  { country: "Riverside", emoji: "🇺🇸", index: 942, type: "city" },
  { country: "Toledo", emoji: "🇺🇸", index: 943, type: "city" },
  { country: "Henderson", emoji: "🇺🇸", index: 944, type: "city" },
  { country: "Modesto", emoji: "🇺🇸", index: 945, type: "city" },
  { country: "Springfield", emoji: "🇺🇸", index: 946, type: "city" },
  { country: "Hollywood", emoji: "🇺🇸", index: 947, type: "city" },
  { country: "Downey", emoji: "🇺🇸", index: 948, type: "city" },
  { country: "Inglewood", emoji: "🇺🇸", index: 949, type: "city" },
  { country: "Duluth", emoji: "🇺🇸", index: 950, type: "city" },
  { country: "Enid", emoji: "🇺🇸", index: 951, type: "city" },
  { country: "Kirkwood", emoji: "🇺🇸", index: 952, type: "city" },
  { country: "Golden", emoji: "🇺🇸", index: 953, type: "city" },
  { country: "Ridgefield", emoji: "🇺🇸", index: 954, type: "city" },
  { country: "Fridley", emoji: "🇺🇸", index: 955, type: "city" },
  { country: "Grosse Pointe Woods", emoji: "🇺🇸", index: 956, type: "city" },
  { country: "Piedmont", emoji: "🇺🇸", index: 957, type: "city" },
  { country: "Windsor", emoji: "🇺🇸", index: 958, type: "city" },
  { country: "Woodside", emoji: "🇺🇸", index: 959, type: "city" },
  { country: "Sydney", emoji: "🇦🇺", index: 960, type: "city" },
  { country: "Edmonton", emoji: "🇨🇦", index: 961, type: "city" },
  { country: "Dongying", emoji: "🇨🇳", index: 962, type: "city" },
  { country: "Medellin", emoji: "🇨🇴", index: 963, type: "city" },
  { country: "Delhi", emoji: "🇮🇳", index: 964, type: "city" },
  { country: "New Delhi", emoji: "🇮🇳", index: 965, type: "city" },
  { country: "Kozhikode", emoji: "🇮🇳", index: 966, type: "city" },
  { country: "Indore", emoji: "🇮🇳", index: 967, type: "city" },
  { country: "Jodhpur", emoji: "🇮🇳", index: 968, type: "city" },
  { country: "Depok", emoji: "🇮🇩", index: 969, type: "city" },
  { country: "Nizhniy Novgorod", emoji: "🇷🇺", index: 970, type: "city" },
  { country: "Rostov-on-Don", emoji: "🇷🇺", index: 971, type: "city" },
  { country: "London", emoji: "🇬🇧", index: 972, type: "city" },
  { country: "Montevideo", emoji: "🇺🇾", index: 973, type: "city" },
  { country: "Egypt", emoji: "🇪🇬", index: 974, type: "country" },
  { country: "Guernsey", emoji: "🇬🇬", index: 975, type: "country" },
  { country: "Jersey", emoji: "🇯🇪", index: 976, type: "country" },
  { country: "Lesotho", emoji: "🇱🇸", index: 977, type: "country" },
  { country: "Montenegro", emoji: "🇲🇪", index: 978, type: "country" },
  { country: "Niger", emoji: "🇳🇪", index: 979, type: "country" },
  { country: "Niue", emoji: "🇳🇺", index: 980, type: "country" },
  { country: "Peru", emoji: "🇵🇪", index: 981, type: "country" },
  { country: "Philippines", emoji: "🇵🇭", index: 982, type: "country" },
  { country: "Reunion", emoji: "🇷🇪", index: 983, type: "country" },
  { country: "Turkey", emoji: "🇹🇷", index: 984, type: "country" },
  { country: "New York", emoji: "🇺🇸", index: 985, type: "city" },
  { country: "Phoenix", emoji: "🇺🇸", index: 986, type: "city" },
  { country: "Memphis", emoji: "🇺🇸", index: 987, type: "city" },
  { country: "Louisville", emoji: "🇺🇸", index: 988, type: "city" },
  { country: "Fresno", emoji: "🇺🇸", index: 989, type: "city" },
  { country: "Lexington", emoji: "🇺🇸", index: 990, type: "city" },
  { country: "Reno", emoji: "🇺🇸", index: 991, type: "city" },
  { country: "Fremont", emoji: "🇺🇸", index: 992, type: "city" },
  { country: "Irvine", emoji: "🇺🇸", index: 993, type: "city" },
  { country: "Yonkers", emoji: "🇺🇸", index: 994, type: "city" },
  { country: "Montgomery", emoji: "🇺🇸", index: 995, type: "city" },
  { country: "Huntsville", emoji: "🇺🇸", index: 996, type: "city" },
  { country: "Tempe", emoji: "🇺🇸", index: 997, type: "city" },
  { country: "Elk Grove", emoji: "🇺🇸", index: 998, type: "city" },
  { country: "Joliet", emoji: "🇺🇸", index: 999, type: "city" },
  { country: "Mesquite", emoji: "🇺🇸", index: 1000, type: "city" },
  { country: "Westminster", emoji: "🇺🇸", index: 1001, type: "city" },
  { country: "Glenview", emoji: "🇺🇸", index: 1002, type: "city" },
  { country: "Perris", emoji: "🇺🇸", index: 1003, type: "city" },
  { country: "Gloversville", emoji: "🇺🇸", index: 1004, type: "city" },
  { country: "Merrillville", emoji: "🇺🇸", index: 1005, type: "city" },
  { country: "Lewistown", emoji: "🇺🇸", index: 1006, type: "city" },
  { country: "River Grove", emoji: "🇺🇸", index: 1007, type: "city" },
  { country: "Green River", emoji: "🇺🇸", index: 1008, type: "city" },
  { country: "Progreso", emoji: "🇺🇸", index: 1009, type: "city" },
  { country: "Yemen", emoji: "🇾🇪", index: 1010, type: "country" },
  { country: "Emeryville", emoji: "🇺🇸", index: 1011, type: "city" },
  { country: "Livermore", emoji: "🇺🇸", index: 1012, type: "city" },
  { country: "Pinole", emoji: "🇺🇸", index: 1013, type: "city" },
  { country: "Perth", emoji: "🇦🇺", index: 1014, type: "city" },
  { country: "Joinville", emoji: "🇧🇷", index: 1015, type: "city" },
  { country: "Phnom Penh", emoji: "🇰🇭", index: 1016, type: "city" },
  { country: "Shenzhen", emoji: "🇨🇳", index: 1017, type: "city" },
  { country: "Zhengzhou", emoji: "🇨🇳", index: 1018, type: "city" },
  { country: "Hefei", emoji: "🇨🇳", index: 1019, type: "city" },
  { country: "Wenzhou", emoji: "🇨🇳", index: 1020, type: "city" },
  { country: "Tengzhou", emoji: "🇨🇳", index: 1021, type: "city" },
  { country: "Luohe", emoji: "🇨🇳", index: 1022, type: "city" },
  { country: "Yueqing", emoji: "🇨🇳", index: 1023, type: "city" },
  { country: "Helsinki", emoji: "🇫🇮", index: 1024, type: "city" },
  { country: "Pune", emoji: "🇮🇳", index: 1025, type: "city" },
  { country: "Meerut", emoji: "🇮🇳", index: 1026, type: "city" },
  { country: "Mysore", emoji: "🇮🇳", index: 1027, type: "city" },
  { country: "Rome", emoji: "🇮🇹", index: 1028, type: "city" },
  { country: "Shimkent", emoji: "🇰🇿", index: 1029, type: "city" },
  { country: "Lilongwe", emoji: "🇲🇼", index: 1030, type: "city" },
  { country: "Monterrey", emoji: "🇲🇽", index: 1031, type: "city" },
  { country: "Fes", emoji: "🇲🇦", index: 1032, type: "city" },
  { country: "Nnewi", emoji: "🇳🇬", index: 1033, type: "city" },
  { country: "Pointe-Noire", emoji: "🇨🇬", index: 1034, type: "city" },
  { country: "Freetown", emoji: "🇸🇱", index: 1035, type: "city" },
  { country: "Ekurhuleni", emoji: "🇿🇦", index: 1036, type: "city" },
  { country: "Seoul", emoji: "🇰🇷", index: 1037, type: "city" },
  { country: "Suweon", emoji: "🇰🇷", index: 1038, type: "city" },
  { country: "Lome", emoji: "🇹🇬", index: 1039, type: "city" },
  { country: "Kiev", emoji: "🇺🇦", index: 1040, type: "city" },
  { country: "West Yorkshire", emoji: "🇬🇧", index: 1041, type: "city" },
  { country: "Fiji", emoji: "🇫🇯", index: 1042, type: "country" },
  { country: "Fort Worth", emoji: "🇺🇸", index: 1043, type: "city" },
  { country: "Norfolk", emoji: "🇺🇸", index: 1044, type: "city" },
  { country: "Fulton", emoji: "🇺🇸", index: 1045, type: "city" },
  { country: "Togo", emoji: "🇹🇬", index: 1046, type: "country" },
  { country: "Irving", emoji: "🇺🇸", index: 1047, type: "city" },
  { country: "Gilroy", emoji: "🇺🇸", index: 1048, type: "city" },
  { country: "Kunming", emoji: "🇨🇳", index: 1049, type: "city" },
  { country: "Xining", emoji: "🇨🇳", index: 1050, type: "city" },
  { country: "Yingkou", emoji: "🇨🇳", index: 1051, type: "city" },
  { country: "Puning", emoji: "🇨🇳", index: 1052, type: "city" },
  { country: "Guilin", emoji: "🇨🇳", index: 1053, type: "city" },
  { country: "Hong Kong", emoji: "🇭🇰", index: 1054, type: "city" },
  { country: "Kingston", emoji: "🇯🇲", index: 1055, type: "city" },
  { country: "Yongin", emoji: "🇰🇷", index: 1056, type: "city" },
  { country: "Houston", emoji: "🇺🇸", index: 1057, type: "city" },
  { country: "Northport", emoji: "🇺🇸", index: 1058, type: "city" },
  { country: "Ohio", emoji: "🇺🇸", index: 1059, type: "city" },
  { country: "Honolulu, HI", emoji: "🇺🇸", index: 1060, type: "city" },
  { country: "Suzhou", emoji: "🇨🇳", index: 1061, type: "city" },
  { country: "Huizhou", emoji: "🇨🇳", index: 1062, type: "city" },
  { country: "Hohhot", emoji: "🇨🇳", index: 1063, type: "city" },
  { country: "Liuzhou", emoji: "🇨🇳", index: 1064, type: "city" },
  { country: "Xuzhou", emoji: "🇨🇳", index: 1065, type: "city" },
  { country: "Zhuzhou", emoji: "🇨🇳", index: 1066, type: "city" },
  { country: "Jinzhou", emoji: "🇨🇳", index: 1067, type: "city" },
  { country: "Pizhou", emoji: "🇨🇳", index: 1068, type: "city" },
  { country: "Thrissur", emoji: "🇮🇳", index: 1069, type: "city" },
  { country: "Homs", emoji: "🇸🇾", index: 1070, type: "city" },
  { country: "St. Louis", emoji: "🇺🇸", index: 1071, type: "city" },
  { country: "Wixom", emoji: "🇺🇸", index: 1072, type: "city" },
  { country: "Illinois", emoji: "🇺🇸", index: 1073, type: "city" },
  { country: "Minsk", emoji: "🇧🇾", index: 1074, type: "city" },
  { country: "Urumqi", emoji: "🇨🇳", index: 1075, type: "city" },
  { country: "Wuxi", emoji: "🇨🇳", index: 1076, type: "city" },
  { country: "Jilin", emoji: "🇨🇳", index: 1077, type: "city" },
  { country: "Yiwu", emoji: "🇨🇳", index: 1078, type: "city" },
  { country: "Zunyi", emoji: "🇨🇳", index: 1079, type: "city" },
  { country: "Quito", emoji: "🇪🇨", index: 1080, type: "city" },
  { country: "Tiruppur", emoji: "🇮🇳", index: 1081, type: "city" },
  { country: "Turin", emoji: "🇮🇹", index: 1082, type: "city" },
  { country: "Tripoli", emoji: "🇱🇾", index: 1083, type: "city" },
  { country: "Tunis", emoji: "🇹🇳", index: 1084, type: "city" },
  { country: "Izmir", emoji: "🇹🇷", index: 1085, type: "city" },
  { country: "Kosovo", emoji: "🇽🇰", index: 1086, type: "country" },
  { country: "Kokomo", emoji: "🇺🇸", index: 1087, type: "city" },
  { country: "Tokyo", emoji: "🇯🇵", index: 1088, type: "city" },
  { country: "Omsk", emoji: "🇷🇺", index: 1089, type: "city" },
  { country: "Lyon", emoji: "🇫🇷", index: 1090, type: "city" },
  { country: "Oslo", emoji: "🇳🇴", index: 1091, type: "city" },
  { country: "Mosul", emoji: "🇮🇶", index: 1092, type: "city" },
  { country: "Qom", emoji: "🇮🇷", index: 1093, type: "city" },
  { country: "Toronto", emoji: "🇨🇦", index: 1094, type: "city" },
  { country: "Ross", emoji: "🇺🇸", index: 1095, type: "city" },
  { country: "Uyo", emoji: "🇳🇬", index: 1096, type: "city" },
  { country: "Porto", emoji: "🇵🇹", index: 1097, type: "city" },
];

export { countryData };
